<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include("$curr_dir/defaultLang.php");
	include("$curr_dir/language.php");
	include("$curr_dir/lib.php");

	// drop-downs config
	$lookups = array(   
		't_registros_publicaciones_ppam_publicador' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdVoluntario' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array('IdPPAM' => 'IdPPAM'),
				'custom_query' => '
SELECT TV.IdVoluntario, `NombreVoluntario`, TV.IdPPAM  FROM t_voluntarios TV LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` 
UNION  SELECT t_voluntarios.IdVoluntario,`NombreVoluntario`, t_voluntarios.IdPPAM FROM `t_colaboraciones_ppam` 
INNER JOIN `t_voluntarios` WHERE t_colaboraciones_ppam.IdVoluntario=t_voluntarios.IdVoluntario order by 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdTurno' => array(
				'parent_table' => 't_turnos',
				'parent_pk_field' => 'IdTurno',
				'parent_caption' => '`t_turnos`.`DescTurno`',
				'parent_from' => '`t_turnos` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdPublicacion' => array(
				'parent_table' => 'm_publicaciones',
				'parent_pk_field' => 'IdPublicacion',
				'parent_caption' => '`m_publicaciones`.`NombrePublicacion`',
				'parent_from' => '`m_publicaciones` LEFT JOIN `m_tipos_publicaciones` as m_tipos_publicaciones1 ON `m_tipos_publicaciones1`.`IdTipoPublicacion`=`m_publicaciones`.`IdTipoPublicacion` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_registro_estudios' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdVoluntario' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array('IdPPAM' => 'IdPPAM'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdPublicacion' => array(
				'parent_table' => 'm_publicaciones',
				'parent_pk_field' => 'IdPublicacion',
				'parent_caption' => '`m_publicaciones`.`NombrePublicacion`',
				'parent_from' => '`m_publicaciones` LEFT JOIN `m_tipos_publicaciones` as m_tipos_publicaciones1 ON `m_tipos_publicaciones1`.`IdTipoPublicacion`=`m_publicaciones`.`IdTipoPublicacion` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_incidencias' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdVoluntario' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array('IdPPAM' => 'IdPPAM'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_turnos_hermanos' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdTurno' => array(
				'parent_table' => 't_turnos',
				'parent_pk_field' => 'IdTurno',
				'parent_caption' => '`t_turnos`.`DescTurno`',
				'parent_from' => '`t_turnos` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdVoluntario' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array('IdPPAM' => 'IdPPAM'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdResponsabilidad' => array(
				'parent_table' => 'm_responsabilidades_ppam',
				'parent_pk_field' => 'IdResponsabilidadPPAM',
				'parent_caption' => '`m_responsabilidades_ppam`.`DescResponsabilidadPPAM`',
				'parent_from' => '`m_responsabilidades_ppam` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_voluntarios' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdResponsabilidadCongregacion' => array(
				'parent_table' => 'm_responsabilidades_congregacion',
				'parent_pk_field' => 'IdResponsabilidad',
				'parent_caption' => '`m_responsabilidades_congregacion`.`DescResponsabilidad`',
				'parent_from' => '`m_responsabilidades_congregacion` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdResponsabilidadPPAM' => array(
				'parent_table' => 'm_responsabilidades_ppam',
				'parent_pk_field' => 'IdResponsabilidadPPAM',
				'parent_caption' => '`m_responsabilidades_ppam`.`DescResponsabilidadPPAM`',
				'parent_from' => '`m_responsabilidades_ppam` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdPrivilegiosServicio' => array(
				'parent_table' => 'm_privilegios_servicio',
				'parent_pk_field' => 'IdPrivilegioServicio',
				'parent_caption' => '`m_privilegios_servicio`.`DescPrivilegioServicio`',
				'parent_from' => '`m_privilegios_servicio` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_colaboraciones_ppam' => array(   
			'IdVoluntario' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_disponibilidades_voluntarios' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdVoluntario' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array('IdPPAM' => 'IdPPAM'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdDiaSemana' => array(
				'parent_table' => 'm_dias_semana',
				'parent_pk_field' => 'IdDiaSemana',
				'parent_caption' => '`m_dias_semana`.`DescDiaSemana`',
				'parent_from' => '`m_dias_semana` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `m_dias_semana`.`IdDiaSemana`, `m_dias_semana`.`DescDiaSemana` FROM `m_dias_semana` ORDER BY 1',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdTurnoDisponible' => array(
				'parent_table' => 't_turnos',
				'parent_pk_field' => 'IdTurno',
				'parent_caption' => '`t_turnos`.`DescTurno`',
				'parent_from' => '`t_turnos` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_turnos_hermanos_maestro' => array(   
			'IdPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdDiaSemana' => array(
				'parent_table' => 'm_dias_semana',
				'parent_pk_field' => 'IdDiaSemana',
				'parent_caption' => '`m_dias_semana`.`DescDiaSemana`',
				'parent_from' => '`m_dias_semana` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `m_dias_semana`.`IdDiaSemana`, `m_dias_semana`.`DescDiaSemana` FROM `m_dias_semana` ORDER BY 1',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdTurno' => array(
				'parent_table' => 't_turnos',
				'parent_pk_field' => 'IdTurno',
				'parent_caption' => '`t_turnos`.`DescTurno`',
				'parent_from' => '`t_turnos` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdVoluntario' => array(
				'parent_table' => 't_disponibilidades_voluntarios',
				'parent_pk_field' => 'IdDisponibilidad',
				'parent_caption' => 'IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS(\'\',   `t_voluntarios1`.`NombreVoluntario`), \'\')',
				'parent_from' => '`t_disponibilidades_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_disponibilidades_voluntarios`.`IdPPAM` LEFT JOIN `t_voluntarios` as t_voluntarios1 ON `t_voluntarios1`.`IdVoluntario`=`t_disponibilidades_voluntarios`.`IdVoluntario` LEFT JOIN `m_dias_semana` as m_dias_semana1 ON `m_dias_semana1`.`IdDiaSemana`=`t_disponibilidades_voluntarios`.`IdDiaSemana` LEFT JOIN `t_turnos` as t_turnos1 ON `t_turnos1`.`IdTurno`=`t_disponibilidades_voluntarios`.`IdTurnoDisponible` ',
				'filterers' => array('IdPPAM' => 'IdPPAM', 'IdDiaSemana' => 'IdDiaSemana', 'IdTurno' => 'IdTurnoDisponible'),
				'custom_query' => 'SELECT `t_disponibilidades_voluntarios`.`IdDisponibilidad`, IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS(\'\',   `t_voluntarios1`.`NombreVoluntario`), \'\') FROM `t_disponibilidades_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_disponibilidades_voluntarios`.`IdPPAM` LEFT JOIN `t_voluntarios` as t_voluntarios1 ON `t_voluntarios1`.`IdVoluntario`=`t_disponibilidades_voluntarios`.`IdVoluntario` LEFT JOIN `m_dias_semana` as m_dias_semana1 ON `m_dias_semana1`.`IdDiaSemana`=`t_disponibilidades_voluntarios`.`IdDiaSemana` LEFT JOIN `t_turnos` as t_turnos1 ON `t_turnos1`.`IdTurno`=`t_disponibilidades_voluntarios`.`IdTurnoDisponible` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'IdResponsabilidad' => array(
				'parent_table' => 'm_responsabilidades_ppam',
				'parent_pk_field' => 'IdResponsabilidadPPAM',
				'parent_caption' => '`m_responsabilidades_ppam`.`DescResponsabilidadPPAM`',
				'parent_from' => '`m_responsabilidades_ppam` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_horarios_calendario_turnos' => array(   
			'idPPAM' => array(
				'parent_table' => 't_ubicaciones_ppam',
				'parent_pk_field' => 'IdPPAM',
				'parent_caption' => '`t_ubicaciones_ppam`.`NombrePPAM`',
				'parent_from' => '`t_ubicaciones_ppam` LEFT JOIN `t_ciudades_ppam` as t_ciudades_ppam1 ON `t_ciudades_ppam1`.`IdCiudadPPAM`=`t_ubicaciones_ppam`.`IdCiudadPPAM` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_ubicaciones_ppam' => array(   
			'IdCiudadPPAM' => array(
				'parent_table' => 't_ciudades_ppam',
				'parent_pk_field' => 'IdCiudadPPAM',
				'parent_caption' => '`t_ciudades_ppam`.`NombreCiudad`',
				'parent_from' => '`t_ciudades_ppam` LEFT JOIN `t_voluntarios` as t_voluntarios1 ON `t_voluntarios1`.`IdVoluntario`=`t_ciudades_ppam`.`IdCoordinador` LEFT JOIN `t_voluntarios` as t_voluntarios2 ON `t_voluntarios2`.`IdVoluntario`=`t_ciudades_ppam`.`idAuxiliarCoordinador1` LEFT JOIN `t_voluntarios` as t_voluntarios3 ON `t_voluntarios3`.`IdVoluntario`=`t_ciudades_ppam`.`idAuxiliarCoordinador2` LEFT JOIN `t_voluntarios` as t_voluntarios4 ON `t_voluntarios4`.`IdVoluntario`=`t_ciudades_ppam`.`idAuxiliarCoordinador3` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		't_ciudades_ppam' => array(   
			'IdCoordinador' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'idAuxiliarCoordinador1' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'idAuxiliarCoordinador2' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'idAuxiliarCoordinador3' => array(
				'parent_table' => 't_voluntarios',
				'parent_pk_field' => 'IdVoluntario',
				'parent_caption' => '`t_voluntarios`.`NombreVoluntario`',
				'parent_from' => '`t_voluntarios` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_voluntarios`.`IdPPAM` LEFT JOIN `m_responsabilidades_congregacion` as m_responsabilidades_congregacion1 ON `m_responsabilidades_congregacion1`.`IdResponsabilidad`=`t_voluntarios`.`IdResponsabilidadCongregacion` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_voluntarios`.`IdResponsabilidadPPAM` LEFT JOIN `m_privilegios_servicio` as m_privilegios_servicio1 ON `m_privilegios_servicio1`.`IdPrivilegioServicio`=`t_voluntarios`.`IdPrivilegiosServicio` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'v_informediarioporppam' => array(  
		),
		'v_informepublicacionesporppamymes' => array(  
		),
		'v_informemensualporciudad' => array(  
		),
		'v_informemensualporpublicador' => array(  
		),
		'v_informeturnosporsemana' => array(  
		),
		'm_publicaciones' => array(   
			'IdTipoPublicacion' => array(
				'parent_table' => 'm_tipos_publicaciones',
				'parent_pk_field' => 'IdTipoPublicacion',
				'parent_caption' => '`m_tipos_publicaciones`.`DescTipoPublicacion`',
				'parent_from' => '`m_tipos_publicaciones` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'm_privilegios_servicio' => array(  
		),
		'm_responsabilidades_ppam' => array(  
		),
		'm_responsabilidades_congregacion' => array(  
		),
		'm_tipos_publicaciones' => array(  
		),
		'm_dias_semana' => array(  
		),
		't_turnos' => array(  
		)
	);


	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(iconv('UTF-8', datalist_db_encoding, $_REQUEST['id']));
	$selected_text = iconv('UTF-8', datalist_db_encoding, $_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(iconv('UTF-8', datalist_db_encoding, $_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm[0] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = array();

	// search term provided?
	if($search_term){
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])){
		foreach($field['filterers'] as $filterer => $filterer_parent){
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get){
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']){
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id){
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)){
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']){
		$qm = array(); $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)){
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)){
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where){
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		}elseif($custom_where){
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		}else{
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = array();
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])){
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		}else{
			$count_query = '';
		}
	}else{
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id){
		$combo->SelectedData = $search_id;
	}elseif($selected_text){
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2){
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions){
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		}else{
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo htmlspecialchars($combo->SelectedData); ?>" />
			<?php
		}
	}else{
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)){
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = array();

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text){
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => $search_id, 'text' => $selected_text);
		}else{
			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)){
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']){
					$prepared_data[] = array('id' => empty_lookup_value, 'text' => "<{$Translation['none']}>");
				}

				$prepared_data[] = array('id' => iconv(datalist_db_encoding, 'UTF-8', $row[0]), 'text' => iconv(datalist_db_encoding, 'UTF-8', $row[1]));
			}
		}

		if(empty($prepared_data)){ $prepared_data[] = array('id' => '', 'text' => $Translation['No matches found!']); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

