<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/m_publicaciones.php");
	include("$currDir/m_publicaciones_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('m_publicaciones');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "m_publicaciones";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`m_publicaciones`.`IdPublicacion`" => "IdPublicacion",
		"`m_publicaciones`.`NombrePublicacion`" => "NombrePublicacion",
		"`m_publicaciones`.`SeUsaParaEstudiar`" => "SeUsaParaEstudiar",
		"IF(    CHAR_LENGTH(`m_tipos_publicaciones1`.`DescTipoPublicacion`), CONCAT_WS('',   `m_tipos_publicaciones1`.`DescTipoPublicacion`), '') /* Tipo Publicaci&oacute;n */" => "IdTipoPublicacion"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`m_publicaciones`.`IdPublicacion`',
		2 => 2,
		3 => '`m_publicaciones`.`SeUsaParaEstudiar`',
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`m_publicaciones`.`IdPublicacion`" => "IdPublicacion",
		"`m_publicaciones`.`NombrePublicacion`" => "NombrePublicacion",
		"`m_publicaciones`.`SeUsaParaEstudiar`" => "SeUsaParaEstudiar",
		"IF(    CHAR_LENGTH(`m_tipos_publicaciones1`.`DescTipoPublicacion`), CONCAT_WS('',   `m_tipos_publicaciones1`.`DescTipoPublicacion`), '') /* Tipo Publicaci&oacute;n */" => "IdTipoPublicacion"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`m_publicaciones`.`IdPublicacion`" => "IdPublicacion",
		"`m_publicaciones`.`NombrePublicacion`" => "Nombre Publicaci&oacute;n",
		"`m_publicaciones`.`SeUsaParaEstudiar`" => "Se usa para Estudios",
		"IF(    CHAR_LENGTH(`m_tipos_publicaciones1`.`DescTipoPublicacion`), CONCAT_WS('',   `m_tipos_publicaciones1`.`DescTipoPublicacion`), '') /* Tipo Publicaci&oacute;n */" => "Tipo Publicaci&oacute;n"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`m_publicaciones`.`IdPublicacion`" => "IdPublicacion",
		"`m_publicaciones`.`NombrePublicacion`" => "NombrePublicacion",
		"`m_publicaciones`.`SeUsaParaEstudiar`" => "SeUsaParaEstudiar",
		"IF(    CHAR_LENGTH(`m_tipos_publicaciones1`.`DescTipoPublicacion`), CONCAT_WS('',   `m_tipos_publicaciones1`.`DescTipoPublicacion`), '') /* Tipo Publicaci&oacute;n */" => "IdTipoPublicacion"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'IdTipoPublicacion' => 'Tipo Publicaci&oacute;n');

	$x->QueryFrom="`m_publicaciones` LEFT JOIN `m_tipos_publicaciones` as m_tipos_publicaciones1 ON `m_tipos_publicaciones1`.`IdTipoPublicacion`=`m_publicaciones`.`IdTipoPublicacion` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "m_publicaciones_view.php";
	$x->RedirectAfterInsert = "m_publicaciones_view.php";
	$x->TableTitle = "Publicaciones";
	$x->TableIcon = "resources/table_icons/align_left.png";
	$x->PrimaryKey = "`m_publicaciones`.`IdPublicacion`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Nombre Publicaci&oacute;n", "Se usa para Estudios", "Tipo Publicaci&oacute;n");
	$x->ColFieldName = array('NombrePublicacion', 'SeUsaParaEstudiar', 'IdTipoPublicacion');
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'templates/m_publicaciones_templateTV.html';
	$x->SelectedTemplate = 'templates/m_publicaciones_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `m_publicaciones`.`IdPublicacion`=membership_userrecords.pkValue and membership_userrecords.tableName='m_publicaciones' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `m_publicaciones`.`IdPublicacion`=membership_userrecords.pkValue and membership_userrecords.tableName='m_publicaciones' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`m_publicaciones`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: m_publicaciones_init
	$render=TRUE;
	if(function_exists('m_publicaciones_init')){
		$args=array();
		$render=m_publicaciones_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: m_publicaciones_header
	$headerCode='';
	if(function_exists('m_publicaciones_header')){
		$args=array();
		$headerCode=m_publicaciones_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: m_publicaciones_footer
	$footerCode='';
	if(function_exists('m_publicaciones_footer')){
		$args=array();
		$footerCode=m_publicaciones_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>