<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/t_ciudades_ppam.php");
	include("$currDir/t_ciudades_ppam_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('t_ciudades_ppam');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "t_ciudades_ppam";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`t_ciudades_ppam`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`t_ciudades_ppam`.`NombreCiudad`" => "NombreCiudad",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Coordinador */" => "IdCoordinador",
		"IF(    CHAR_LENGTH(`t_voluntarios2`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios2`.`NombreVoluntario`), '') /* Auxiliar 1 Coordinador */" => "idAuxiliarCoordinador1",
		"IF(    CHAR_LENGTH(`t_voluntarios3`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios3`.`NombreVoluntario`), '') /* Auxiliar 2 Coordinador */" => "idAuxiliarCoordinador2",
		"IF(    CHAR_LENGTH(`t_voluntarios4`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios4`.`NombreVoluntario`), '') /* Auxiliar 3 Coordinador */" => "idAuxiliarCoordinador3"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`t_ciudades_ppam`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`t_ciudades_ppam`.`NombreCiudad`" => "NombreCiudad",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Coordinador */" => "IdCoordinador",
		"IF(    CHAR_LENGTH(`t_voluntarios2`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios2`.`NombreVoluntario`), '') /* Auxiliar 1 Coordinador */" => "idAuxiliarCoordinador1",
		"IF(    CHAR_LENGTH(`t_voluntarios3`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios3`.`NombreVoluntario`), '') /* Auxiliar 2 Coordinador */" => "idAuxiliarCoordinador2",
		"IF(    CHAR_LENGTH(`t_voluntarios4`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios4`.`NombreVoluntario`), '') /* Auxiliar 3 Coordinador */" => "idAuxiliarCoordinador3"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`t_ciudades_ppam`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`t_ciudades_ppam`.`NombreCiudad`" => "NombreCiudad",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Coordinador */" => "Coordinador",
		"IF(    CHAR_LENGTH(`t_voluntarios2`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios2`.`NombreVoluntario`), '') /* Auxiliar 1 Coordinador */" => "Auxiliar 1 Coordinador",
		"IF(    CHAR_LENGTH(`t_voluntarios3`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios3`.`NombreVoluntario`), '') /* Auxiliar 2 Coordinador */" => "Auxiliar 2 Coordinador",
		"IF(    CHAR_LENGTH(`t_voluntarios4`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios4`.`NombreVoluntario`), '') /* Auxiliar 3 Coordinador */" => "Auxiliar 3 Coordinador"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`t_ciudades_ppam`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`t_ciudades_ppam`.`NombreCiudad`" => "NombreCiudad",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Coordinador */" => "IdCoordinador",
		"IF(    CHAR_LENGTH(`t_voluntarios2`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios2`.`NombreVoluntario`), '') /* Auxiliar 1 Coordinador */" => "idAuxiliarCoordinador1",
		"IF(    CHAR_LENGTH(`t_voluntarios3`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios3`.`NombreVoluntario`), '') /* Auxiliar 2 Coordinador */" => "idAuxiliarCoordinador2",
		"IF(    CHAR_LENGTH(`t_voluntarios4`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios4`.`NombreVoluntario`), '') /* Auxiliar 3 Coordinador */" => "idAuxiliarCoordinador3"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'IdCoordinador' => 'Coordinador', 'idAuxiliarCoordinador1' => 'Auxiliar 1 Coordinador', 'idAuxiliarCoordinador2' => 'Auxiliar 2 Coordinador', 'idAuxiliarCoordinador3' => 'Auxiliar 3 Coordinador');

	$x->QueryFrom="`t_ciudades_ppam` LEFT JOIN `t_voluntarios` as t_voluntarios1 ON `t_voluntarios1`.`IdVoluntario`=`t_ciudades_ppam`.`IdCoordinador` LEFT JOIN `t_voluntarios` as t_voluntarios2 ON `t_voluntarios2`.`IdVoluntario`=`t_ciudades_ppam`.`idAuxiliarCoordinador1` LEFT JOIN `t_voluntarios` as t_voluntarios3 ON `t_voluntarios3`.`IdVoluntario`=`t_ciudades_ppam`.`idAuxiliarCoordinador2` LEFT JOIN `t_voluntarios` as t_voluntarios4 ON `t_voluntarios4`.`IdVoluntario`=`t_ciudades_ppam`.`idAuxiliarCoordinador3` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "t_ciudades_ppam_view.php";
	$x->RedirectAfterInsert = "t_ciudades_ppam_view.php";
	$x->TableTitle = "Ciudades PPAM";
	$x->TableIcon = "resources/table_icons/orbit.png";
	$x->PrimaryKey = "`t_ciudades_ppam`.`IdCiudadPPAM`";
// FGS	$x->DefaultSortField = '1';
// FGS	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("NombreCiudad", "Coordinador", "Auxiliar 1 Coordinador", "Auxiliar 2 Coordinador", "Auxiliar 3 Coordinador");
	$x->ColFieldName = array('NombreCiudad', 'IdCoordinador', 'idAuxiliarCoordinador1', 'idAuxiliarCoordinador2', 'idAuxiliarCoordinador3');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	$x->Template = 'templates/t_ciudades_ppam_templateTV.html';
	$x->SelectedTemplate = 'templates/t_ciudades_ppam_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

// FGS - EL CODIGO ESTA EN EL HOOK
/*
	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_ciudades_ppam`.`IdCiudadPPAM`=membership_userrecords.pkValue and membership_userrecords.tableName='t_ciudades_ppam' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_ciudades_ppam`.`IdCiudadPPAM`=membership_userrecords.pkValue and membership_userrecords.tableName='t_ciudades_ppam' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`t_ciudades_ppam`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
*/
	// hook: t_ciudades_ppam_init
	$render=TRUE;
	if(function_exists('t_ciudades_ppam_init')){
		$args=array();
		$render=t_ciudades_ppam_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: t_ciudades_ppam_header
	$headerCode='';
	if(function_exists('t_ciudades_ppam_header')){
		$args=array();
		$headerCode=t_ciudades_ppam_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: t_ciudades_ppam_footer
	$footerCode='';
	if(function_exists('t_ciudades_ppam_footer')){
		$args=array();
		$footerCode=t_ciudades_ppam_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>