<?php

// Data functions (insert, update, delete, form) for table t_ciudades_ppam

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function t_ciudades_ppam_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('t_ciudades_ppam');
	if(!$arrPerm[1]){
		return false;
	}

	$data['IdCiudadPPAM'] = makeSafe($_REQUEST['IdCiudadPPAM']);
		if($data['IdCiudadPPAM'] == empty_lookup_value){ $data['IdCiudadPPAM'] = ''; }
	$data['NombreCiudad'] = makeSafe($_REQUEST['NombreCiudad']);
		if($data['NombreCiudad'] == empty_lookup_value){ $data['NombreCiudad'] = ''; }
	$data['IdCoordinador'] = makeSafe($_REQUEST['IdCoordinador']);
		if($data['IdCoordinador'] == empty_lookup_value){ $data['IdCoordinador'] = ''; }
	$data['idAuxiliarCoordinador1'] = makeSafe($_REQUEST['idAuxiliarCoordinador1']);
		if($data['idAuxiliarCoordinador1'] == empty_lookup_value){ $data['idAuxiliarCoordinador1'] = ''; }
	$data['idAuxiliarCoordinador2'] = makeSafe($_REQUEST['idAuxiliarCoordinador2']);
		if($data['idAuxiliarCoordinador2'] == empty_lookup_value){ $data['idAuxiliarCoordinador2'] = ''; }
	$data['idAuxiliarCoordinador3'] = makeSafe($_REQUEST['idAuxiliarCoordinador3']);
		if($data['idAuxiliarCoordinador3'] == empty_lookup_value){ $data['idAuxiliarCoordinador3'] = ''; }
	if($data['IdCiudadPPAM'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'IdCiudadPPAM': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: t_ciudades_ppam_before_insert
	if(function_exists('t_ciudades_ppam_before_insert')){
		$args=array();
		if(!t_ciudades_ppam_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `t_ciudades_ppam` set       `NombreCiudad`=' . (($data['NombreCiudad'] !== '' && $data['NombreCiudad'] !== NULL) ? "'{$data['NombreCiudad']}'" : 'NULL') . ', `IdCoordinador`=' . (($data['IdCoordinador'] !== '' && $data['IdCoordinador'] !== NULL) ? "'{$data['IdCoordinador']}'" : 'NULL') . ', `idAuxiliarCoordinador1`=' . (($data['idAuxiliarCoordinador1'] !== '' && $data['idAuxiliarCoordinador1'] !== NULL) ? "'{$data['idAuxiliarCoordinador1']}'" : 'NULL') . ', `idAuxiliarCoordinador2`=' . (($data['idAuxiliarCoordinador2'] !== '' && $data['idAuxiliarCoordinador2'] !== NULL) ? "'{$data['idAuxiliarCoordinador2']}'" : 'NULL') . ', `idAuxiliarCoordinador3`=' . (($data['idAuxiliarCoordinador3'] !== '' && $data['idAuxiliarCoordinador3'] !== NULL) ? "'{$data['idAuxiliarCoordinador3']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"t_ciudades_ppam_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['IdCiudadPPAM'];

	// hook: t_ciudades_ppam_after_insert
	if(function_exists('t_ciudades_ppam_after_insert')){
		$res = sql("select * from `t_ciudades_ppam` where `IdCiudadPPAM`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!t_ciudades_ppam_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='t_ciudades_ppam', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function t_ciudades_ppam_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('t_ciudades_ppam');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: t_ciudades_ppam_before_delete
	if(function_exists('t_ciudades_ppam_before_delete')){
		$args=array();
		if(!t_ciudades_ppam_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: t_ubicaciones_ppam
	$res = sql("select `IdCiudadPPAM` from `t_ciudades_ppam` where `IdCiudadPPAM`='$selected_id'", $eo);
	$IdCiudadPPAM = db_fetch_row($res);
	$rires = sql("select count(1) from `t_ubicaciones_ppam` where `IdCiudadPPAM`='".addslashes($IdCiudadPPAM[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ubicaciones_ppam", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ubicaciones_ppam", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_ciudades_ppam_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_ciudades_ppam_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `t_ciudades_ppam` where `IdCiudadPPAM`='$selected_id'", $eo);

	// hook: t_ciudades_ppam_after_delete
	if(function_exists('t_ciudades_ppam_after_delete')){
		$args=array();
		t_ciudades_ppam_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='$selected_id'", $eo);
}

function t_ciudades_ppam_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('t_ciudades_ppam');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['IdCiudadPPAM'] = makeSafe($_REQUEST['IdCiudadPPAM']);
		if($data['IdCiudadPPAM'] == empty_lookup_value){ $data['IdCiudadPPAM'] = ''; }
	$data['NombreCiudad'] = makeSafe($_REQUEST['NombreCiudad']);
		if($data['NombreCiudad'] == empty_lookup_value){ $data['NombreCiudad'] = ''; }
	$data['IdCoordinador'] = makeSafe($_REQUEST['IdCoordinador']);
		if($data['IdCoordinador'] == empty_lookup_value){ $data['IdCoordinador'] = ''; }
	$data['idAuxiliarCoordinador1'] = makeSafe($_REQUEST['idAuxiliarCoordinador1']);
		if($data['idAuxiliarCoordinador1'] == empty_lookup_value){ $data['idAuxiliarCoordinador1'] = ''; }
	$data['idAuxiliarCoordinador2'] = makeSafe($_REQUEST['idAuxiliarCoordinador2']);
		if($data['idAuxiliarCoordinador2'] == empty_lookup_value){ $data['idAuxiliarCoordinador2'] = ''; }
	$data['idAuxiliarCoordinador3'] = makeSafe($_REQUEST['idAuxiliarCoordinador3']);
		if($data['idAuxiliarCoordinador3'] == empty_lookup_value){ $data['idAuxiliarCoordinador3'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: t_ciudades_ppam_before_update
	if(function_exists('t_ciudades_ppam_before_update')){
		$args=array();
		if(!t_ciudades_ppam_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `t_ciudades_ppam` set       `NombreCiudad`=' . (($data['NombreCiudad'] !== '' && $data['NombreCiudad'] !== NULL) ? "'{$data['NombreCiudad']}'" : 'NULL') . ', `IdCoordinador`=' . (($data['IdCoordinador'] !== '' && $data['IdCoordinador'] !== NULL) ? "'{$data['IdCoordinador']}'" : 'NULL') . ', `idAuxiliarCoordinador1`=' . (($data['idAuxiliarCoordinador1'] !== '' && $data['idAuxiliarCoordinador1'] !== NULL) ? "'{$data['idAuxiliarCoordinador1']}'" : 'NULL') . ', `idAuxiliarCoordinador2`=' . (($data['idAuxiliarCoordinador2'] !== '' && $data['idAuxiliarCoordinador2'] !== NULL) ? "'{$data['idAuxiliarCoordinador2']}'" : 'NULL') . ', `idAuxiliarCoordinador3`=' . (($data['idAuxiliarCoordinador3'] !== '' && $data['idAuxiliarCoordinador3'] !== NULL) ? "'{$data['idAuxiliarCoordinador3']}'" : 'NULL') . " where `IdCiudadPPAM`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="t_ciudades_ppam_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['IdCiudadPPAM'];

	// hook: t_ciudades_ppam_after_update
	if(function_exists('t_ciudades_ppam_after_update')){
		$res = sql("SELECT * FROM `t_ciudades_ppam` WHERE `IdCiudadPPAM`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['IdCiudadPPAM'];
		$args = array();
		if(!t_ciudades_ppam_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['IdCiudadPPAM']}' where tableName='t_ciudades_ppam' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function t_ciudades_ppam_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('t_ciudades_ppam');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_IdCoordinador = thisOr(undo_magic_quotes($_REQUEST['filterer_IdCoordinador']), '');
	$filterer_idAuxiliarCoordinador1 = thisOr(undo_magic_quotes($_REQUEST['filterer_idAuxiliarCoordinador1']), '');
	$filterer_idAuxiliarCoordinador2 = thisOr(undo_magic_quotes($_REQUEST['filterer_idAuxiliarCoordinador2']), '');
	$filterer_idAuxiliarCoordinador3 = thisOr(undo_magic_quotes($_REQUEST['filterer_idAuxiliarCoordinador3']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: IdCoordinador
	$combo_IdCoordinador = new DataCombo;
	// combobox: idAuxiliarCoordinador1
	$combo_idAuxiliarCoordinador1 = new DataCombo;
	// combobox: idAuxiliarCoordinador2
	$combo_idAuxiliarCoordinador2 = new DataCombo;
	// combobox: idAuxiliarCoordinador3
	$combo_idAuxiliarCoordinador3 = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_ciudades_ppam' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `t_ciudades_ppam` where `IdCiudadPPAM`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_IdCoordinador->SelectedData = $row['IdCoordinador'];
		$combo_idAuxiliarCoordinador1->SelectedData = $row['idAuxiliarCoordinador1'];
		$combo_idAuxiliarCoordinador2->SelectedData = $row['idAuxiliarCoordinador2'];
		$combo_idAuxiliarCoordinador3->SelectedData = $row['idAuxiliarCoordinador3'];
	}else{
		$combo_IdCoordinador->SelectedData = $filterer_IdCoordinador;
		$combo_idAuxiliarCoordinador1->SelectedData = $filterer_idAuxiliarCoordinador1;
		$combo_idAuxiliarCoordinador2->SelectedData = $filterer_idAuxiliarCoordinador2;
		$combo_idAuxiliarCoordinador3->SelectedData = $filterer_idAuxiliarCoordinador3;
	}
	$combo_IdCoordinador->HTML = '<span id="IdCoordinador-container' . $rnd1 . '"></span><input type="hidden" name="IdCoordinador" id="IdCoordinador' . $rnd1 . '" value="' . htmlspecialchars($combo_IdCoordinador->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdCoordinador->MatchText = '<span id="IdCoordinador-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdCoordinador" id="IdCoordinador' . $rnd1 . '" value="' . htmlspecialchars($combo_IdCoordinador->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idAuxiliarCoordinador1->HTML = '<span id="idAuxiliarCoordinador1-container' . $rnd1 . '"></span><input type="hidden" name="idAuxiliarCoordinador1" id="idAuxiliarCoordinador1' . $rnd1 . '" value="' . htmlspecialchars($combo_idAuxiliarCoordinador1->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idAuxiliarCoordinador1->MatchText = '<span id="idAuxiliarCoordinador1-container-readonly' . $rnd1 . '"></span><input type="hidden" name="idAuxiliarCoordinador1" id="idAuxiliarCoordinador1' . $rnd1 . '" value="' . htmlspecialchars($combo_idAuxiliarCoordinador1->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idAuxiliarCoordinador2->HTML = '<span id="idAuxiliarCoordinador2-container' . $rnd1 . '"></span><input type="hidden" name="idAuxiliarCoordinador2" id="idAuxiliarCoordinador2' . $rnd1 . '" value="' . htmlspecialchars($combo_idAuxiliarCoordinador2->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idAuxiliarCoordinador2->MatchText = '<span id="idAuxiliarCoordinador2-container-readonly' . $rnd1 . '"></span><input type="hidden" name="idAuxiliarCoordinador2" id="idAuxiliarCoordinador2' . $rnd1 . '" value="' . htmlspecialchars($combo_idAuxiliarCoordinador2->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idAuxiliarCoordinador3->HTML = '<span id="idAuxiliarCoordinador3-container' . $rnd1 . '"></span><input type="hidden" name="idAuxiliarCoordinador3" id="idAuxiliarCoordinador3' . $rnd1 . '" value="' . htmlspecialchars($combo_idAuxiliarCoordinador3->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idAuxiliarCoordinador3->MatchText = '<span id="idAuxiliarCoordinador3-container-readonly' . $rnd1 . '"></span><input type="hidden" name="idAuxiliarCoordinador3" id="idAuxiliarCoordinador3' . $rnd1 . '" value="' . htmlspecialchars($combo_idAuxiliarCoordinador3->SelectedData, ENT_QUOTES, 'UTF-8') . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_IdCoordinador__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdCoordinador'] : $filterer_IdCoordinador); ?>"};
		var current_idAuxiliarCoordinador1__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['idAuxiliarCoordinador1'] : $filterer_idAuxiliarCoordinador1); ?>"};
		var current_idAuxiliarCoordinador2__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['idAuxiliarCoordinador2'] : $filterer_idAuxiliarCoordinador2); ?>"};
		var current_idAuxiliarCoordinador3__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['idAuxiliarCoordinador3'] : $filterer_idAuxiliarCoordinador3); ?>"};

		jQuery(function() {
			if(typeof(IdCoordinador_reload__RAND__) == 'function') IdCoordinador_reload__RAND__();
			if(typeof(idAuxiliarCoordinador1_reload__RAND__) == 'function') idAuxiliarCoordinador1_reload__RAND__();
			if(typeof(idAuxiliarCoordinador2_reload__RAND__) == 'function') idAuxiliarCoordinador2_reload__RAND__();
			if(typeof(idAuxiliarCoordinador3_reload__RAND__) == 'function') idAuxiliarCoordinador3_reload__RAND__();
		});
		function IdCoordinador_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdCoordinador-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdCoordinador__RAND__.value, t: 't_ciudades_ppam', f: 'IdCoordinador' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdCoordinador"]').val(resp.results[0].id);
						jQuery('[id=IdCoordinador-container-readonly__RAND__]').html('<span id="IdCoordinador-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdCoordinador_update_autofills__RAND__) == 'function') IdCoordinador_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_ciudades_ppam', f: 'IdCoordinador' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdCoordinador__RAND__.value = e.added.id;
				current_IdCoordinador__RAND__.text = e.added.text;
				jQuery('[name="IdCoordinador"]').val(e.added.id);


				if(typeof(IdCoordinador_update_autofills__RAND__) == 'function') IdCoordinador_update_autofills__RAND__();
			});

			if(!$j("#IdCoordinador-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdCoordinador__RAND__.value, t: 't_ciudades_ppam', f: 'IdCoordinador' }
				}).done(function(resp){
					$j('[name="IdCoordinador"]').val(resp.results[0].id);
					$j('[id=IdCoordinador-container-readonly__RAND__]').html('<span id="IdCoordinador-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdCoordinador_update_autofills__RAND__) == 'function') IdCoordinador_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdCoordinador__RAND__.value, t: 't_ciudades_ppam', f: 'IdCoordinador' }
			}).done(function(resp){
				jQuery('[id=IdCoordinador-container__RAND__], [id=IdCoordinador-container-readonly__RAND__]').html('<span id="IdCoordinador-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdCoordinador_update_autofills__RAND__) == 'function') IdCoordinador_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function idAuxiliarCoordinador1_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#idAuxiliarCoordinador1-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_idAuxiliarCoordinador1__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador1' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="idAuxiliarCoordinador1"]').val(resp.results[0].id);
						jQuery('[id=idAuxiliarCoordinador1-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador1-match-text">' + resp.results[0].text + '</span>');


						if(typeof(idAuxiliarCoordinador1_update_autofills__RAND__) == 'function') idAuxiliarCoordinador1_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador1' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_idAuxiliarCoordinador1__RAND__.value = e.added.id;
				current_idAuxiliarCoordinador1__RAND__.text = e.added.text;
				jQuery('[name="idAuxiliarCoordinador1"]').val(e.added.id);


				if(typeof(idAuxiliarCoordinador1_update_autofills__RAND__) == 'function') idAuxiliarCoordinador1_update_autofills__RAND__();
			});

			if(!$j("#idAuxiliarCoordinador1-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_idAuxiliarCoordinador1__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador1' }
				}).done(function(resp){
					$j('[name="idAuxiliarCoordinador1"]').val(resp.results[0].id);
					$j('[id=idAuxiliarCoordinador1-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador1-match-text">' + resp.results[0].text + '</span>');

					if(typeof(idAuxiliarCoordinador1_update_autofills__RAND__) == 'function') idAuxiliarCoordinador1_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_idAuxiliarCoordinador1__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador1' }
			}).done(function(resp){
				jQuery('[id=idAuxiliarCoordinador1-container__RAND__], [id=idAuxiliarCoordinador1-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador1-match-text">' + resp.results[0].text + '</span>');

				if(typeof(idAuxiliarCoordinador1_update_autofills__RAND__) == 'function') idAuxiliarCoordinador1_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function idAuxiliarCoordinador2_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#idAuxiliarCoordinador2-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_idAuxiliarCoordinador2__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador2' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="idAuxiliarCoordinador2"]').val(resp.results[0].id);
						jQuery('[id=idAuxiliarCoordinador2-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador2-match-text">' + resp.results[0].text + '</span>');


						if(typeof(idAuxiliarCoordinador2_update_autofills__RAND__) == 'function') idAuxiliarCoordinador2_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador2' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_idAuxiliarCoordinador2__RAND__.value = e.added.id;
				current_idAuxiliarCoordinador2__RAND__.text = e.added.text;
				jQuery('[name="idAuxiliarCoordinador2"]').val(e.added.id);


				if(typeof(idAuxiliarCoordinador2_update_autofills__RAND__) == 'function') idAuxiliarCoordinador2_update_autofills__RAND__();
			});

			if(!$j("#idAuxiliarCoordinador2-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_idAuxiliarCoordinador2__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador2' }
				}).done(function(resp){
					$j('[name="idAuxiliarCoordinador2"]').val(resp.results[0].id);
					$j('[id=idAuxiliarCoordinador2-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador2-match-text">' + resp.results[0].text + '</span>');

					if(typeof(idAuxiliarCoordinador2_update_autofills__RAND__) == 'function') idAuxiliarCoordinador2_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_idAuxiliarCoordinador2__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador2' }
			}).done(function(resp){
				jQuery('[id=idAuxiliarCoordinador2-container__RAND__], [id=idAuxiliarCoordinador2-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador2-match-text">' + resp.results[0].text + '</span>');

				if(typeof(idAuxiliarCoordinador2_update_autofills__RAND__) == 'function') idAuxiliarCoordinador2_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function idAuxiliarCoordinador3_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#idAuxiliarCoordinador3-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_idAuxiliarCoordinador3__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador3' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="idAuxiliarCoordinador3"]').val(resp.results[0].id);
						jQuery('[id=idAuxiliarCoordinador3-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador3-match-text">' + resp.results[0].text + '</span>');


						if(typeof(idAuxiliarCoordinador3_update_autofills__RAND__) == 'function') idAuxiliarCoordinador3_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador3' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_idAuxiliarCoordinador3__RAND__.value = e.added.id;
				current_idAuxiliarCoordinador3__RAND__.text = e.added.text;
				jQuery('[name="idAuxiliarCoordinador3"]').val(e.added.id);


				if(typeof(idAuxiliarCoordinador3_update_autofills__RAND__) == 'function') idAuxiliarCoordinador3_update_autofills__RAND__();
			});

			if(!$j("#idAuxiliarCoordinador3-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_idAuxiliarCoordinador3__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador3' }
				}).done(function(resp){
					$j('[name="idAuxiliarCoordinador3"]').val(resp.results[0].id);
					$j('[id=idAuxiliarCoordinador3-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador3-match-text">' + resp.results[0].text + '</span>');

					if(typeof(idAuxiliarCoordinador3_update_autofills__RAND__) == 'function') idAuxiliarCoordinador3_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_idAuxiliarCoordinador3__RAND__.value, t: 't_ciudades_ppam', f: 'idAuxiliarCoordinador3' }
			}).done(function(resp){
				jQuery('[id=idAuxiliarCoordinador3-container__RAND__], [id=idAuxiliarCoordinador3-container-readonly__RAND__]').html('<span id="idAuxiliarCoordinador3-match-text">' + resp.results[0].text + '</span>');

				if(typeof(idAuxiliarCoordinador3_update_autofills__RAND__) == 'function') idAuxiliarCoordinador3_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/t_ciudades_ppam_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle del Registro', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return t_ciudades_ppam_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return t_ciudades_ppam_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return t_ciudades_ppam_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#NombreCiudad').replaceWith('<div class=\"form-control-static\" id=\"NombreCiudad\">' + (jQuery('#NombreCiudad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#IdCoordinador').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdCoordinador_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#idAuxiliarCoordinador1').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#idAuxiliarCoordinador1_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#idAuxiliarCoordinador2').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#idAuxiliarCoordinador2_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#idAuxiliarCoordinador3').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#idAuxiliarCoordinador3_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(IdCoordinador)%%>', $combo_IdCoordinador->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdCoordinador)%%>', $combo_IdCoordinador->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdCoordinador)%%>', urlencode($combo_IdCoordinador->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(idAuxiliarCoordinador1)%%>', $combo_idAuxiliarCoordinador1->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(idAuxiliarCoordinador1)%%>', $combo_idAuxiliarCoordinador1->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(idAuxiliarCoordinador1)%%>', urlencode($combo_idAuxiliarCoordinador1->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(idAuxiliarCoordinador2)%%>', $combo_idAuxiliarCoordinador2->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(idAuxiliarCoordinador2)%%>', $combo_idAuxiliarCoordinador2->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(idAuxiliarCoordinador2)%%>', urlencode($combo_idAuxiliarCoordinador2->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(idAuxiliarCoordinador3)%%>', $combo_idAuxiliarCoordinador3->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(idAuxiliarCoordinador3)%%>', $combo_idAuxiliarCoordinador3->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(idAuxiliarCoordinador3)%%>', urlencode($combo_idAuxiliarCoordinador3->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'IdCoordinador' => array('t_voluntarios', 'Coordinador'), 'idAuxiliarCoordinador1' => array('t_voluntarios', 'Auxiliar 1 Coordinador'), 'idAuxiliarCoordinador2' => array('t_voluntarios', 'Auxiliar 2 Coordinador'), 'idAuxiliarCoordinador3' => array('t_voluntarios', 'Auxiliar 3 Coordinador'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(IdCiudadPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(NombreCiudad)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdCoordinador)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(idAuxiliarCoordinador1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(idAuxiliarCoordinador2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(idAuxiliarCoordinador3)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(IdCiudadPPAM)%%>', htmlspecialchars($row['IdCiudadPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdCiudadPPAM)%%>', urlencode($urow['IdCiudadPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(NombreCiudad)%%>', htmlspecialchars($row['NombreCiudad'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NombreCiudad)%%>', urlencode($urow['NombreCiudad']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdCoordinador)%%>', htmlspecialchars($row['IdCoordinador'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdCoordinador)%%>', urlencode($urow['IdCoordinador']), $templateCode);
		$templateCode=str_replace('<%%VALUE(idAuxiliarCoordinador1)%%>', htmlspecialchars($row['idAuxiliarCoordinador1'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idAuxiliarCoordinador1)%%>', urlencode($urow['idAuxiliarCoordinador1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(idAuxiliarCoordinador2)%%>', htmlspecialchars($row['idAuxiliarCoordinador2'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idAuxiliarCoordinador2)%%>', urlencode($urow['idAuxiliarCoordinador2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(idAuxiliarCoordinador3)%%>', htmlspecialchars($row['idAuxiliarCoordinador3'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idAuxiliarCoordinador3)%%>', urlencode($urow['idAuxiliarCoordinador3']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(IdCiudadPPAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdCiudadPPAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(NombreCiudad)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NombreCiudad)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdCoordinador)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdCoordinador)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(idAuxiliarCoordinador1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idAuxiliarCoordinador1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(idAuxiliarCoordinador2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idAuxiliarCoordinador2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(idAuxiliarCoordinador3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idAuxiliarCoordinador3)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: t_ciudades_ppam_dv
	if(function_exists('t_ciudades_ppam_dv')){
		$args=array();
		t_ciudades_ppam_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>