<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/t_horarios_calendario_turnos.php");
	include("$currDir/t_horarios_calendario_turnos_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('t_horarios_calendario_turnos');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "t_horarios_calendario_turnos";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`t_horarios_calendario_turnos`.`idHorarioCalendario`" => "idHorarioCalendario",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "idPPAM",
		"`t_horarios_calendario_turnos`.`InicioTurno1`" => "InicioTurno1",
		"`t_horarios_calendario_turnos`.`FinTurno1`" => "FinTurno1",
		"`t_horarios_calendario_turnos`.`InicioTurno2`" => "InicioTurno2",
		"`t_horarios_calendario_turnos`.`FinTurno2`" => "FinTurno2",
		"`t_horarios_calendario_turnos`.`InicioTurno3`" => "InicioTurno3",
		"`t_horarios_calendario_turnos`.`FinTurno3`" => "FinTurno3",
		"`t_horarios_calendario_turnos`.`InicioTurno4`" => "InicioTurno4",
		"`t_horarios_calendario_turnos`.`FinTurno4`" => "FinTurno4"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`t_horarios_calendario_turnos`.`idHorarioCalendario`" => "idHorarioCalendario",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "idPPAM",
		"`t_horarios_calendario_turnos`.`InicioTurno1`" => "InicioTurno1",
		"`t_horarios_calendario_turnos`.`FinTurno1`" => "FinTurno1",
		"`t_horarios_calendario_turnos`.`InicioTurno2`" => "InicioTurno2",
		"`t_horarios_calendario_turnos`.`FinTurno2`" => "FinTurno2",
		"`t_horarios_calendario_turnos`.`InicioTurno3`" => "InicioTurno3",
		"`t_horarios_calendario_turnos`.`FinTurno3`" => "FinTurno3",
		"`t_horarios_calendario_turnos`.`InicioTurno4`" => "InicioTurno4",
		"`t_horarios_calendario_turnos`.`FinTurno4`" => "FinTurno4"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`t_horarios_calendario_turnos`.`idHorarioCalendario`" => "IdHorarioCalendario",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "PPAM",
		"`t_horarios_calendario_turnos`.`InicioTurno1`" => "Inicio Turno 1",
		"`t_horarios_calendario_turnos`.`FinTurno1`" => "Fin Turno 1",
		"`t_horarios_calendario_turnos`.`InicioTurno2`" => "Inicio Turno 2",
		"`t_horarios_calendario_turnos`.`FinTurno2`" => "Fin Turno 2",
		"`t_horarios_calendario_turnos`.`InicioTurno3`" => "Inicio Turno 3",
		"`t_horarios_calendario_turnos`.`FinTurno3`" => "Fin Turno 3",
		"`t_horarios_calendario_turnos`.`InicioTurno4`" => "Inicio Turno 4",
		"`t_horarios_calendario_turnos`.`FinTurno4`" => "Fin Turno 4"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`t_horarios_calendario_turnos`.`idHorarioCalendario`" => "idHorarioCalendario",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "idPPAM",
		"`t_horarios_calendario_turnos`.`InicioTurno1`" => "InicioTurno1",
		"`t_horarios_calendario_turnos`.`FinTurno1`" => "FinTurno1",
		"`t_horarios_calendario_turnos`.`InicioTurno2`" => "InicioTurno2",
		"`t_horarios_calendario_turnos`.`FinTurno2`" => "FinTurno2",
		"`t_horarios_calendario_turnos`.`InicioTurno3`" => "InicioTurno3",
		"`t_horarios_calendario_turnos`.`FinTurno3`" => "FinTurno3",
		"`t_horarios_calendario_turnos`.`InicioTurno4`" => "InicioTurno4",
		"`t_horarios_calendario_turnos`.`FinTurno4`" => "FinTurno4"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'idPPAM' => 'PPAM');

	$x->QueryFrom="`t_horarios_calendario_turnos` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_horarios_calendario_turnos`.`idPPAM` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 0;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "t_horarios_calendario_turnos_view.php";
	$x->RedirectAfterInsert = "t_horarios_calendario_turnos_view.php";
	$x->TableTitle = "Horarios Calen. Turnos";
	$x->TableIcon = "resources/table_icons/clock_15.png";
	$x->PrimaryKey = "`t_horarios_calendario_turnos`.`idHorarioCalendario`";
// FGS	$x->DefaultSortField = '2';
// FGS	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("PPAM", "Inicio Turno 1", "Fin Turno 1", "Inicio Turno 2", "Fin Turno 2", "Inicio Turno 3", "Fin Turno 3", "Inicio Turno 4", "Fin Turno 4");
	$x->ColFieldName = array('idPPAM', 'InicioTurno1', 'FinTurno1', 'InicioTurno2', 'FinTurno2', 'InicioTurno3', 'FinTurno3', 'InicioTurno4', 'FinTurno4');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	$x->Template = 'templates/t_horarios_calendario_turnos_templateTV.html';
	$x->SelectedTemplate = 'templates/t_horarios_calendario_turnos_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

/* FGS - EL CODIGO ESTA EN EL HOOK
	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_horarios_calendario_turnos`.`idHorarioCalendario`=membership_userrecords.pkValue and membership_userrecords.tableName='t_horarios_calendario_turnos' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_horarios_calendario_turnos`.`idHorarioCalendario`=membership_userrecords.pkValue and membership_userrecords.tableName='t_horarios_calendario_turnos' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`t_horarios_calendario_turnos`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
*/
	// hook: t_horarios_calendario_turnos_init
	$render=TRUE;
	if(function_exists('t_horarios_calendario_turnos_init')){
		$args=array();
		$render=t_horarios_calendario_turnos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: t_horarios_calendario_turnos_header
	$headerCode='';
	if(function_exists('t_horarios_calendario_turnos_header')){
		$args=array();
		$headerCode=t_horarios_calendario_turnos_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: t_horarios_calendario_turnos_footer
	$footerCode='';
	if(function_exists('t_horarios_calendario_turnos_footer')){
		$args=array();
		$footerCode=t_horarios_calendario_turnos_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>