<?php

// Data functions (insert, update, delete, form) for table t_horarios_calendario_turnos

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function t_horarios_calendario_turnos_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('t_horarios_calendario_turnos');
	if(!$arrPerm[1]){
		return false;
	}

	$data['idHorarioCalendario'] = makeSafe($_REQUEST['idHorarioCalendario']);
		if($data['idHorarioCalendario'] == empty_lookup_value){ $data['idHorarioCalendario'] = ''; }
	$data['idPPAM'] = makeSafe($_REQUEST['idPPAM']);
		if($data['idPPAM'] == empty_lookup_value){ $data['idPPAM'] = ''; }
	$data['InicioTurno1'] = makeSafe($_REQUEST['InicioTurno1']);
		if($data['InicioTurno1'] == empty_lookup_value){ $data['InicioTurno1'] = ''; }
	$data['FinTurno1'] = makeSafe($_REQUEST['FinTurno1']);
		if($data['FinTurno1'] == empty_lookup_value){ $data['FinTurno1'] = ''; }
	$data['InicioTurno2'] = makeSafe($_REQUEST['InicioTurno2']);
		if($data['InicioTurno2'] == empty_lookup_value){ $data['InicioTurno2'] = ''; }
	$data['FinTurno2'] = makeSafe($_REQUEST['FinTurno2']);
		if($data['FinTurno2'] == empty_lookup_value){ $data['FinTurno2'] = ''; }
	$data['InicioTurno3'] = makeSafe($_REQUEST['InicioTurno3']);
		if($data['InicioTurno3'] == empty_lookup_value){ $data['InicioTurno3'] = ''; }
	$data['FinTurno3'] = makeSafe($_REQUEST['FinTurno3']);
		if($data['FinTurno3'] == empty_lookup_value){ $data['FinTurno3'] = ''; }
	$data['InicioTurno4'] = makeSafe($_REQUEST['InicioTurno4']);
		if($data['InicioTurno4'] == empty_lookup_value){ $data['InicioTurno4'] = ''; }
	$data['FinTurno4'] = makeSafe($_REQUEST['FinTurno4']);
		if($data['FinTurno4'] == empty_lookup_value){ $data['FinTurno4'] = ''; }
	if($data['idHorarioCalendario'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'IdHorarioCalendario': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: t_horarios_calendario_turnos_before_insert
	if(function_exists('t_horarios_calendario_turnos_before_insert')){
		$args=array();
		if(!t_horarios_calendario_turnos_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `t_horarios_calendario_turnos` set       `idPPAM`=' . (($data['idPPAM'] !== '' && $data['idPPAM'] !== NULL) ? "'{$data['idPPAM']}'" : 'NULL') . ', `InicioTurno1`=' . (($data['InicioTurno1'] !== '' && $data['InicioTurno1'] !== NULL) ? "'{$data['InicioTurno1']}'" : 'NULL') . ', `FinTurno1`=' . (($data['FinTurno1'] !== '' && $data['FinTurno1'] !== NULL) ? "'{$data['FinTurno1']}'" : 'NULL') . ', `InicioTurno2`=' . (($data['InicioTurno2'] !== '' && $data['InicioTurno2'] !== NULL) ? "'{$data['InicioTurno2']}'" : 'NULL') . ', `FinTurno2`=' . (($data['FinTurno2'] !== '' && $data['FinTurno2'] !== NULL) ? "'{$data['FinTurno2']}'" : 'NULL') . ', `InicioTurno3`=' . (($data['InicioTurno3'] !== '' && $data['InicioTurno3'] !== NULL) ? "'{$data['InicioTurno3']}'" : 'NULL') . ', `FinTurno3`=' . (($data['FinTurno3'] !== '' && $data['FinTurno3'] !== NULL) ? "'{$data['FinTurno3']}'" : 'NULL') . ', `InicioTurno4`=' . (($data['InicioTurno4'] !== '' && $data['InicioTurno4'] !== NULL) ? "'{$data['InicioTurno4']}'" : 'NULL') . ', `FinTurno4`=' . (($data['FinTurno4'] !== '' && $data['FinTurno4'] !== NULL) ? "'{$data['FinTurno4']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"t_horarios_calendario_turnos_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['idHorarioCalendario'];

	// hook: t_horarios_calendario_turnos_after_insert
	if(function_exists('t_horarios_calendario_turnos_after_insert')){
		$res = sql("select * from `t_horarios_calendario_turnos` where `idHorarioCalendario`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!t_horarios_calendario_turnos_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='t_horarios_calendario_turnos', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function t_horarios_calendario_turnos_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('t_horarios_calendario_turnos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: t_horarios_calendario_turnos_before_delete
	if(function_exists('t_horarios_calendario_turnos_before_delete')){
		$args=array();
		if(!t_horarios_calendario_turnos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `t_horarios_calendario_turnos` where `idHorarioCalendario`='$selected_id'", $eo);

	// hook: t_horarios_calendario_turnos_after_delete
	if(function_exists('t_horarios_calendario_turnos_after_delete')){
		$args=array();
		t_horarios_calendario_turnos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='$selected_id'", $eo);
}

function t_horarios_calendario_turnos_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('t_horarios_calendario_turnos');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['idHorarioCalendario'] = makeSafe($_REQUEST['idHorarioCalendario']);
		if($data['idHorarioCalendario'] == empty_lookup_value){ $data['idHorarioCalendario'] = ''; }
	$data['idPPAM'] = makeSafe($_REQUEST['idPPAM']);
		if($data['idPPAM'] == empty_lookup_value){ $data['idPPAM'] = ''; }
	$data['InicioTurno1'] = makeSafe($_REQUEST['InicioTurno1']);
		if($data['InicioTurno1'] == empty_lookup_value){ $data['InicioTurno1'] = ''; }
	$data['FinTurno1'] = makeSafe($_REQUEST['FinTurno1']);
		if($data['FinTurno1'] == empty_lookup_value){ $data['FinTurno1'] = ''; }
	$data['InicioTurno2'] = makeSafe($_REQUEST['InicioTurno2']);
		if($data['InicioTurno2'] == empty_lookup_value){ $data['InicioTurno2'] = ''; }
	$data['FinTurno2'] = makeSafe($_REQUEST['FinTurno2']);
		if($data['FinTurno2'] == empty_lookup_value){ $data['FinTurno2'] = ''; }
	$data['InicioTurno3'] = makeSafe($_REQUEST['InicioTurno3']);
		if($data['InicioTurno3'] == empty_lookup_value){ $data['InicioTurno3'] = ''; }
	$data['FinTurno3'] = makeSafe($_REQUEST['FinTurno3']);
		if($data['FinTurno3'] == empty_lookup_value){ $data['FinTurno3'] = ''; }
	$data['InicioTurno4'] = makeSafe($_REQUEST['InicioTurno4']);
		if($data['InicioTurno4'] == empty_lookup_value){ $data['InicioTurno4'] = ''; }
	$data['FinTurno4'] = makeSafe($_REQUEST['FinTurno4']);
		if($data['FinTurno4'] == empty_lookup_value){ $data['FinTurno4'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: t_horarios_calendario_turnos_before_update
	if(function_exists('t_horarios_calendario_turnos_before_update')){
		$args=array();
		if(!t_horarios_calendario_turnos_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `t_horarios_calendario_turnos` set       `idPPAM`=' . (($data['idPPAM'] !== '' && $data['idPPAM'] !== NULL) ? "'{$data['idPPAM']}'" : 'NULL') . ', `InicioTurno1`=' . (($data['InicioTurno1'] !== '' && $data['InicioTurno1'] !== NULL) ? "'{$data['InicioTurno1']}'" : 'NULL') . ', `FinTurno1`=' . (($data['FinTurno1'] !== '' && $data['FinTurno1'] !== NULL) ? "'{$data['FinTurno1']}'" : 'NULL') . ', `InicioTurno2`=' . (($data['InicioTurno2'] !== '' && $data['InicioTurno2'] !== NULL) ? "'{$data['InicioTurno2']}'" : 'NULL') . ', `FinTurno2`=' . (($data['FinTurno2'] !== '' && $data['FinTurno2'] !== NULL) ? "'{$data['FinTurno2']}'" : 'NULL') . ', `InicioTurno3`=' . (($data['InicioTurno3'] !== '' && $data['InicioTurno3'] !== NULL) ? "'{$data['InicioTurno3']}'" : 'NULL') . ', `FinTurno3`=' . (($data['FinTurno3'] !== '' && $data['FinTurno3'] !== NULL) ? "'{$data['FinTurno3']}'" : 'NULL') . ', `InicioTurno4`=' . (($data['InicioTurno4'] !== '' && $data['InicioTurno4'] !== NULL) ? "'{$data['InicioTurno4']}'" : 'NULL') . ', `FinTurno4`=' . (($data['FinTurno4'] !== '' && $data['FinTurno4'] !== NULL) ? "'{$data['FinTurno4']}'" : 'NULL') . " where `idHorarioCalendario`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="t_horarios_calendario_turnos_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['idHorarioCalendario'];

	// hook: t_horarios_calendario_turnos_after_update
	if(function_exists('t_horarios_calendario_turnos_after_update')){
		$res = sql("SELECT * FROM `t_horarios_calendario_turnos` WHERE `idHorarioCalendario`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['idHorarioCalendario'];
		$args = array();
		if(!t_horarios_calendario_turnos_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['idHorarioCalendario']}' where tableName='t_horarios_calendario_turnos' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function t_horarios_calendario_turnos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('t_horarios_calendario_turnos');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_idPPAM = thisOr(undo_magic_quotes($_REQUEST['filterer_idPPAM']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: idPPAM
	$combo_idPPAM = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_horarios_calendario_turnos' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `t_horarios_calendario_turnos` where `idHorarioCalendario`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_idPPAM->SelectedData = $row['idPPAM'];
	}else{
		$combo_idPPAM->SelectedData = $filterer_idPPAM;
	}
	$combo_idPPAM->HTML = '<span id="idPPAM-container' . $rnd1 . '"></span><input type="hidden" name="idPPAM" id="idPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_idPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_idPPAM->MatchText = '<span id="idPPAM-container-readonly' . $rnd1 . '"></span><input type="hidden" name="idPPAM" id="idPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_idPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_idPPAM__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['idPPAM'] : $filterer_idPPAM); ?>"};

		jQuery(function() {
			if(typeof(idPPAM_reload__RAND__) == 'function') idPPAM_reload__RAND__();
		});
		function idPPAM_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#idPPAM-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_idPPAM__RAND__.value, t: 't_horarios_calendario_turnos', f: 'idPPAM' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="idPPAM"]').val(resp.results[0].id);
						jQuery('[id=idPPAM-container-readonly__RAND__]').html('<span id="idPPAM-match-text">' + resp.results[0].text + '</span>');


						if(typeof(idPPAM_update_autofills__RAND__) == 'function') idPPAM_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_horarios_calendario_turnos', f: 'idPPAM' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_idPPAM__RAND__.value = e.added.id;
				current_idPPAM__RAND__.text = e.added.text;
				jQuery('[name="idPPAM"]').val(e.added.id);


				if(typeof(idPPAM_update_autofills__RAND__) == 'function') idPPAM_update_autofills__RAND__();
			});

			if(!$j("#idPPAM-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_idPPAM__RAND__.value, t: 't_horarios_calendario_turnos', f: 'idPPAM' }
				}).done(function(resp){
					$j('[name="idPPAM"]').val(resp.results[0].id);
					$j('[id=idPPAM-container-readonly__RAND__]').html('<span id="idPPAM-match-text">' + resp.results[0].text + '</span>');

					if(typeof(idPPAM_update_autofills__RAND__) == 'function') idPPAM_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_idPPAM__RAND__.value, t: 't_horarios_calendario_turnos', f: 'idPPAM' }
			}).done(function(resp){
				jQuery('[id=idPPAM-container__RAND__], [id=idPPAM-container-readonly__RAND__]').html('<span id="idPPAM-match-text">' + resp.results[0].text + '</span>');

				if(typeof(idPPAM_update_autofills__RAND__) == 'function') idPPAM_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/t_horarios_calendario_turnos_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle del Registro', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return t_horarios_calendario_turnos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return t_horarios_calendario_turnos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return t_horarios_calendario_turnos_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#idPPAM').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#idPPAM_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#InicioTurno1').replaceWith('<div class=\"form-control-static\" id=\"InicioTurno1\">' + (jQuery('#InicioTurno1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FinTurno1').replaceWith('<div class=\"form-control-static\" id=\"FinTurno1\">' + (jQuery('#FinTurno1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#InicioTurno2').replaceWith('<div class=\"form-control-static\" id=\"InicioTurno2\">' + (jQuery('#InicioTurno2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FinTurno2').replaceWith('<div class=\"form-control-static\" id=\"FinTurno2\">' + (jQuery('#FinTurno2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#InicioTurno3').replaceWith('<div class=\"form-control-static\" id=\"InicioTurno3\">' + (jQuery('#InicioTurno3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FinTurno3').replaceWith('<div class=\"form-control-static\" id=\"FinTurno3\">' + (jQuery('#FinTurno3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#InicioTurno4').replaceWith('<div class=\"form-control-static\" id=\"InicioTurno4\">' + (jQuery('#InicioTurno4').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FinTurno4').replaceWith('<div class=\"form-control-static\" id=\"FinTurno4\">' + (jQuery('#FinTurno4').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(idPPAM)%%>', $combo_idPPAM->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(idPPAM)%%>', $combo_idPPAM->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(idPPAM)%%>', urlencode($combo_idPPAM->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'idPPAM' => array('t_ubicaciones_ppam', 'PPAM'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(idHorarioCalendario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(idPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(InicioTurno1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FinTurno1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(InicioTurno2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FinTurno2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(InicioTurno3)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FinTurno3)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(InicioTurno4)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FinTurno4)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(idHorarioCalendario)%%>', htmlspecialchars($row['idHorarioCalendario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idHorarioCalendario)%%>', urlencode($urow['idHorarioCalendario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(idPPAM)%%>', htmlspecialchars($row['idPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idPPAM)%%>', urlencode($urow['idPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno1)%%>', htmlspecialchars($row['InicioTurno1'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno1)%%>', urlencode($urow['InicioTurno1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno1)%%>', htmlspecialchars($row['FinTurno1'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno1)%%>', urlencode($urow['FinTurno1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno2)%%>', htmlspecialchars($row['InicioTurno2'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno2)%%>', urlencode($urow['InicioTurno2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno2)%%>', htmlspecialchars($row['FinTurno2'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno2)%%>', urlencode($urow['FinTurno2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno3)%%>', htmlspecialchars($row['InicioTurno3'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno3)%%>', urlencode($urow['InicioTurno3']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno3)%%>', htmlspecialchars($row['FinTurno3'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno3)%%>', urlencode($urow['FinTurno3']), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno4)%%>', htmlspecialchars($row['InicioTurno4'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno4)%%>', urlencode($urow['InicioTurno4']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno4)%%>', htmlspecialchars($row['FinTurno4'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno4)%%>', urlencode($urow['FinTurno4']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(idHorarioCalendario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idHorarioCalendario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(idPPAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(idPPAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno3)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno3)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(InicioTurno4)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InicioTurno4)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FinTurno4)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FinTurno4)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: t_horarios_calendario_turnos_dv
	if(function_exists('t_horarios_calendario_turnos_dv')){
		$args=array();
		t_horarios_calendario_turnos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>