<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/t_incidencias.php");
	include("$currDir/t_incidencias_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('t_incidencias');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "t_incidencias";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`t_incidencias`.`IdIncidencia`" => "IdIncidencia",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "IdPPAM",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "IdVoluntario",
		"if(`t_incidencias`.`FechaIncidencia`,date_format(`t_incidencias`.`FechaIncidencia`,'%d-%m-%Y'),'')" => "FechaIncidencia",
		"if(`t_incidencias`.`FechaRegistro`,date_format(`t_incidencias`.`FechaRegistro`,'%d-%m-%Y'),'')" => "FechaRegistro",
		"`t_incidencias`.`DescIncidencia`" => "DescIncidencia"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`t_incidencias`.`IdIncidencia`',
		2 => 2,
		3 => 3,
		4 => '`t_incidencias`.`FechaIncidencia`',
		5 => '`t_incidencias`.`FechaRegistro`',
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`t_incidencias`.`IdIncidencia`" => "IdIncidencia",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "IdPPAM",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "IdVoluntario",
		"if(`t_incidencias`.`FechaIncidencia`,date_format(`t_incidencias`.`FechaIncidencia`,'%d-%m-%Y'),'')" => "FechaIncidencia",
		"if(`t_incidencias`.`FechaRegistro`,date_format(`t_incidencias`.`FechaRegistro`,'%d-%m-%Y'),'')" => "FechaRegistro",
		"`t_incidencias`.`DescIncidencia`" => "DescIncidencia"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`t_incidencias`.`IdIncidencia`" => "IdIncidencia",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "PPAM",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "Voluntario",
		"`t_incidencias`.`FechaIncidencia`" => "Fecha Incidencia",
		"`t_incidencias`.`FechaRegistro`" => "FechaRegistro",
		"`t_incidencias`.`DescIncidencia`" => "Raz&oacute;n Incidencia"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`t_incidencias`.`IdIncidencia`" => "IdIncidencia",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "IdPPAM",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "IdVoluntario",
		"if(`t_incidencias`.`FechaIncidencia`,date_format(`t_incidencias`.`FechaIncidencia`,'%d-%m-%Y'),'')" => "FechaIncidencia",
		"if(`t_incidencias`.`FechaRegistro`,date_format(`t_incidencias`.`FechaRegistro`,'%d-%m-%Y'),'')" => "FechaRegistro",
		"`t_incidencias`.`DescIncidencia`" => "DescIncidencia"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'IdPPAM' => 'PPAM', 'IdVoluntario' => 'Voluntario');

	$x->QueryFrom="`t_incidencias` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_incidencias`.`IdPPAM` LEFT JOIN `t_voluntarios` as t_voluntarios1 ON `t_voluntarios1`.`IdVoluntario`=`t_incidencias`.`IdVoluntario` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "t_incidencias_view.php";
	$x->RedirectAfterInsert = "t_incidencias_view.php?SelectedID=#ID#";
	$x->TableTitle = "Incidencias";
	$x->TableIcon = "resources/table_icons/alarm_bell.png";
	$x->PrimaryKey = "`t_incidencias`.`IdIncidencia`";
// FGS	$x->DefaultSortField = '2';
// FGS	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("PPAM", "Voluntario", "Fecha Incidencia", "Raz&oacute;n Incidencia");
	$x->ColFieldName = array('IdPPAM', 'IdVoluntario', 'FechaIncidencia', 'DescIncidencia');
	$x->ColNumber  = array(2, 3, 4, 6);

	$x->Template = 'templates/t_incidencias_templateTV.html';
	$x->SelectedTemplate = 'templates/t_incidencias_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

/* FGS - EL CODIGO ESTA EN EL HOOK
	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_incidencias`.`IdIncidencia`=membership_userrecords.pkValue and membership_userrecords.tableName='t_incidencias' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_incidencias`.`IdIncidencia`=membership_userrecords.pkValue and membership_userrecords.tableName='t_incidencias' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`t_incidencias`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
*/
	// hook: t_incidencias_init
	$render=TRUE;
	if(function_exists('t_incidencias_init')){
		$args=array();
		$render=t_incidencias_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: t_incidencias_header
	$headerCode='';
	if(function_exists('t_incidencias_header')){
		$args=array();
		$headerCode=t_incidencias_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: t_incidencias_footer
	$footerCode='';
	if(function_exists('t_incidencias_footer')){
		$args=array();
		$footerCode=t_incidencias_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>