<?php

// Data functions (insert, update, delete, form) for table t_registro_estudios

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function t_registro_estudios_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('t_registro_estudios');
	if(!$arrPerm[1]){
		return false;
	}

	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['IdVoluntario'] = makeSafe($_REQUEST['IdVoluntario']);
		if($data['IdVoluntario'] == empty_lookup_value){ $data['IdVoluntario'] = ''; }
	$data['NombreEstudiante'] = makeSafe($_REQUEST['NombreEstudiante']);
		if($data['NombreEstudiante'] == empty_lookup_value){ $data['NombreEstudiante'] = ''; }
	$data['IdPublicacion'] = makeSafe($_REQUEST['IdPublicacion']);
		if($data['IdPublicacion'] == empty_lookup_value){ $data['IdPublicacion'] = ''; }
	$data['Capitulo'] = makeSafe($_REQUEST['Capitulo']);
		if($data['Capitulo'] == empty_lookup_value){ $data['Capitulo'] = ''; }
	$data['Parrafo'] = makeSafe($_REQUEST['Parrafo']);
		if($data['Parrafo'] == empty_lookup_value){ $data['Parrafo'] = ''; }
	$data['Observaciones'] = makeSafe($_REQUEST['Observaciones']);
		if($data['Observaciones'] == empty_lookup_value){ $data['Observaciones'] = ''; }

	// hook: t_registro_estudios_before_insert
	if(function_exists('t_registro_estudios_before_insert')){
		$args=array();
		if(!t_registro_estudios_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `t_registro_estudios` set       `IdPPAM`=' . (($data['IdPPAM'] !== '' && $data['IdPPAM'] !== NULL) ? "'{$data['IdPPAM']}'" : 'NULL') . ', `IdVoluntario`=' . (($data['IdVoluntario'] !== '' && $data['IdVoluntario'] !== NULL) ? "'{$data['IdVoluntario']}'" : 'NULL') . ', `NombreEstudiante`=' . (($data['NombreEstudiante'] !== '' && $data['NombreEstudiante'] !== NULL) ? "'{$data['NombreEstudiante']}'" : 'NULL') . ', `IdPublicacion`=' . (($data['IdPublicacion'] !== '' && $data['IdPublicacion'] !== NULL) ? "'{$data['IdPublicacion']}'" : 'NULL') . ', `Capitulo`=' . (($data['Capitulo'] !== '' && $data['Capitulo'] !== NULL) ? "'{$data['Capitulo']}'" : 'NULL') . ', `Parrafo`=' . (($data['Parrafo'] !== '' && $data['Parrafo'] !== NULL) ? "'{$data['Parrafo']}'" : 'NULL') . ', `Observaciones`=' . (($data['Observaciones'] !== '' && $data['Observaciones'] !== NULL) ? "'{$data['Observaciones']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"t_registro_estudios_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: t_registro_estudios_after_insert
	if(function_exists('t_registro_estudios_after_insert')){
		$res = sql("select * from `t_registro_estudios` where `IdRegistroEstudios`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!t_registro_estudios_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='t_registro_estudios', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function t_registro_estudios_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('t_registro_estudios');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_registro_estudios' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_registro_estudios' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: t_registro_estudios_before_delete
	if(function_exists('t_registro_estudios_before_delete')){
		$args=array();
		if(!t_registro_estudios_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `t_registro_estudios` where `IdRegistroEstudios`='$selected_id'", $eo);

	// hook: t_registro_estudios_after_delete
	if(function_exists('t_registro_estudios_after_delete')){
		$args=array();
		t_registro_estudios_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='t_registro_estudios' and pkValue='$selected_id'", $eo);
}

function t_registro_estudios_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('t_registro_estudios');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_registro_estudios' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_registro_estudios' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['IdVoluntario'] = makeSafe($_REQUEST['IdVoluntario']);
		if($data['IdVoluntario'] == empty_lookup_value){ $data['IdVoluntario'] = ''; }
	$data['NombreEstudiante'] = makeSafe($_REQUEST['NombreEstudiante']);
		if($data['NombreEstudiante'] == empty_lookup_value){ $data['NombreEstudiante'] = ''; }
	$data['IdPublicacion'] = makeSafe($_REQUEST['IdPublicacion']);
		if($data['IdPublicacion'] == empty_lookup_value){ $data['IdPublicacion'] = ''; }
	$data['Capitulo'] = makeSafe($_REQUEST['Capitulo']);
		if($data['Capitulo'] == empty_lookup_value){ $data['Capitulo'] = ''; }
	$data['Parrafo'] = makeSafe($_REQUEST['Parrafo']);
		if($data['Parrafo'] == empty_lookup_value){ $data['Parrafo'] = ''; }
	$data['Observaciones'] = makeSafe($_REQUEST['Observaciones']);
		if($data['Observaciones'] == empty_lookup_value){ $data['Observaciones'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: t_registro_estudios_before_update
	if(function_exists('t_registro_estudios_before_update')){
		$args=array();
		if(!t_registro_estudios_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `t_registro_estudios` set       `IdPPAM`=' . (($data['IdPPAM'] !== '' && $data['IdPPAM'] !== NULL) ? "'{$data['IdPPAM']}'" : 'NULL') . ', `IdVoluntario`=' . (($data['IdVoluntario'] !== '' && $data['IdVoluntario'] !== NULL) ? "'{$data['IdVoluntario']}'" : 'NULL') . ', `NombreEstudiante`=' . (($data['NombreEstudiante'] !== '' && $data['NombreEstudiante'] !== NULL) ? "'{$data['NombreEstudiante']}'" : 'NULL') . ', `IdPublicacion`=' . (($data['IdPublicacion'] !== '' && $data['IdPublicacion'] !== NULL) ? "'{$data['IdPublicacion']}'" : 'NULL') . ', `Capitulo`=' . (($data['Capitulo'] !== '' && $data['Capitulo'] !== NULL) ? "'{$data['Capitulo']}'" : 'NULL') . ', `Parrafo`=' . (($data['Parrafo'] !== '' && $data['Parrafo'] !== NULL) ? "'{$data['Parrafo']}'" : 'NULL') . ', `Observaciones`=' . (($data['Observaciones'] !== '' && $data['Observaciones'] !== NULL) ? "'{$data['Observaciones']}'" : 'NULL') . " where `IdRegistroEstudios`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="t_registro_estudios_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: t_registro_estudios_after_update
	if(function_exists('t_registro_estudios_after_update')){
		$res = sql("SELECT * FROM `t_registro_estudios` WHERE `IdRegistroEstudios`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['IdRegistroEstudios'];
		$args = array();
		if(!t_registro_estudios_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='t_registro_estudios' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function t_registro_estudios_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('t_registro_estudios');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_IdPPAM = thisOr(undo_magic_quotes($_REQUEST['filterer_IdPPAM']), '');
	$filterer_IdVoluntario = thisOr(undo_magic_quotes($_REQUEST['filterer_IdVoluntario']), '');
	$filterer_IdPublicacion = thisOr(undo_magic_quotes($_REQUEST['filterer_IdPublicacion']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_IdVoluntario && !$filterer_IdPPAM) $filterer_IdPPAM = sqlValue("select IdPPAM from t_voluntarios where IdVoluntario='" . makeSafe($filterer_IdVoluntario) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: IdPPAM
	$combo_IdPPAM = new DataCombo;
	// combobox: IdVoluntario, filterable by: IdPPAM
	$combo_IdVoluntario = new DataCombo;
	// combobox: IdPublicacion
	$combo_IdPublicacion = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_registro_estudios' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_registro_estudios' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `t_registro_estudios` where `IdRegistroEstudios`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_IdPPAM->SelectedData = $row['IdPPAM'];
		$combo_IdVoluntario->SelectedData = $row['IdVoluntario'];
		$combo_IdPublicacion->SelectedData = $row['IdPublicacion'];
	}else{
		$combo_IdPPAM->SelectedData = $filterer_IdPPAM;
		$combo_IdVoluntario->SelectedData = $filterer_IdVoluntario;
		$combo_IdPublicacion->SelectedData = $filterer_IdPublicacion;
	}
	$combo_IdPPAM->HTML = '<span id="IdPPAM-container' . $rnd1 . '"></span><input type="hidden" name="IdPPAM" id="IdPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPPAM->MatchText = '<span id="IdPPAM-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdPPAM" id="IdPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdVoluntario->HTML = '<span id="IdVoluntario-container' . $rnd1 . '"></span><input type="hidden" name="IdVoluntario" id="IdVoluntario' . $rnd1 . '" value="' . htmlspecialchars($combo_IdVoluntario->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdVoluntario->MatchText = '<span id="IdVoluntario-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdVoluntario" id="IdVoluntario' . $rnd1 . '" value="' . htmlspecialchars($combo_IdVoluntario->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPublicacion->HTML = '<span id="IdPublicacion-container' . $rnd1 . '"></span><input type="hidden" name="IdPublicacion" id="IdPublicacion' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPublicacion->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPublicacion->MatchText = '<span id="IdPublicacion-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdPublicacion" id="IdPublicacion' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPublicacion->SelectedData, ENT_QUOTES, 'UTF-8') . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_IdPPAM__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdPPAM'] : $filterer_IdPPAM); ?>"};
		var current_IdVoluntario__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdVoluntario'] : $filterer_IdVoluntario); ?>"};
		var current_IdPublicacion__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdPublicacion'] : $filterer_IdPublicacion); ?>"};

		jQuery(function() {
			if(typeof(IdPPAM_reload__RAND__) == 'function') IdPPAM_reload__RAND__();
			<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(IdVoluntario_reload__RAND__) == \'function\') IdVoluntario_reload__RAND__(current_IdPPAM__RAND__.value);' : ''); ?>
			if(typeof(IdPublicacion_reload__RAND__) == 'function') IdPublicacion_reload__RAND__();
		});
		function IdPPAM_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdPPAM-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdPPAM__RAND__.value, t: 't_registro_estudios', f: 'IdPPAM' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdPPAM"]').val(resp.results[0].id);
						jQuery('[id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__(current_IdPPAM__RAND__.value);

						if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_registro_estudios', f: 'IdPPAM' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdPPAM__RAND__.value = e.added.id;
				current_IdPPAM__RAND__.text = e.added.text;
				jQuery('[name="IdPPAM"]').val(e.added.id);

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__(current_IdPPAM__RAND__.value);

				if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
			});

			if(!$j("#IdPPAM-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdPPAM__RAND__.value, t: 't_registro_estudios', f: 'IdPPAM' }
				}).done(function(resp){
					$j('[name="IdPPAM"]').val(resp.results[0].id);
					$j('[id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdPPAM__RAND__.value, t: 't_registro_estudios', f: 'IdPPAM' }
			}).done(function(resp){
				jQuery('[id=IdPPAM-container__RAND__], [id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdVoluntario_reload__RAND__(filterer_IdPPAM){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdVoluntario-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_IdPPAM: filterer_IdPPAM, id: current_IdVoluntario__RAND__.value, t: 't_registro_estudios', f: 'IdVoluntario' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdVoluntario"]').val(resp.results[0].id);
						jQuery('[id=IdVoluntario-container-readonly__RAND__]').html('<span id="IdVoluntario-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { filterer_IdPPAM: filterer_IdPPAM, s: term, p: page, t: 't_registro_estudios', f: 'IdVoluntario' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdVoluntario__RAND__.value = e.added.id;
				current_IdVoluntario__RAND__.text = e.added.text;
				jQuery('[name="IdVoluntario"]').val(e.added.id);


				if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
			});

			if(!$j("#IdVoluntario-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdVoluntario__RAND__.value, t: 't_registro_estudios', f: 'IdVoluntario' }
				}).done(function(resp){
					$j('[name="IdVoluntario"]').val(resp.results[0].id);
					$j('[id=IdVoluntario-container-readonly__RAND__]').html('<span id="IdVoluntario-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdVoluntario__RAND__.value, t: 't_registro_estudios', f: 'IdVoluntario' }
			}).done(function(resp){
				jQuery('[id=IdVoluntario-container__RAND__], [id=IdVoluntario-container-readonly__RAND__]').html('<span id="IdVoluntario-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdPublicacion_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdPublicacion-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdPublicacion__RAND__.value, t: 't_registro_estudios', f: 'IdPublicacion' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdPublicacion"]').val(resp.results[0].id);
						jQuery('[id=IdPublicacion-container-readonly__RAND__]').html('<span id="IdPublicacion-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdPublicacion_update_autofills__RAND__) == 'function') IdPublicacion_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_registro_estudios', f: 'IdPublicacion' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdPublicacion__RAND__.value = e.added.id;
				current_IdPublicacion__RAND__.text = e.added.text;
				jQuery('[name="IdPublicacion"]').val(e.added.id);


				if(typeof(IdPublicacion_update_autofills__RAND__) == 'function') IdPublicacion_update_autofills__RAND__();
			});

			if(!$j("#IdPublicacion-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdPublicacion__RAND__.value, t: 't_registro_estudios', f: 'IdPublicacion' }
				}).done(function(resp){
					$j('[name="IdPublicacion"]').val(resp.results[0].id);
					$j('[id=IdPublicacion-container-readonly__RAND__]').html('<span id="IdPublicacion-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdPublicacion_update_autofills__RAND__) == 'function') IdPublicacion_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdPublicacion__RAND__.value, t: 't_registro_estudios', f: 'IdPublicacion' }
			}).done(function(resp){
				jQuery('[id=IdPublicacion-container__RAND__], [id=IdPublicacion-container-readonly__RAND__]').html('<span id="IdPublicacion-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdPublicacion_update_autofills__RAND__) == 'function') IdPublicacion_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/t_registro_estudios_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle del Registro', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return t_registro_estudios_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return t_registro_estudios_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return t_registro_estudios_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#IdPPAM').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdPPAM_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdVoluntario').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdVoluntario_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#NombreEstudiante').replaceWith('<div class=\"form-control-static\" id=\"NombreEstudiante\">' + (jQuery('#NombreEstudiante').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#IdPublicacion').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdPublicacion_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Capitulo').replaceWith('<div class=\"form-control-static\" id=\"Capitulo\">' + (jQuery('#Capitulo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Parrafo').replaceWith('<div class=\"form-control-static\" id=\"Parrafo\">' + (jQuery('#Parrafo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Observaciones').replaceWith('<div class=\"form-control-static\" id=\"Observaciones\">' + (jQuery('#Observaciones').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(IdPPAM)%%>', $combo_IdPPAM->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdPPAM)%%>', $combo_IdPPAM->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdPPAM)%%>', urlencode($combo_IdPPAM->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdVoluntario)%%>', $combo_IdVoluntario->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdVoluntario)%%>', $combo_IdVoluntario->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdVoluntario)%%>', urlencode($combo_IdVoluntario->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdPublicacion)%%>', $combo_IdPublicacion->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdPublicacion)%%>', $combo_IdPublicacion->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdPublicacion)%%>', urlencode($combo_IdPublicacion->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'IdPPAM' => array('t_ubicaciones_ppam', 'PPAM'), 'IdVoluntario' => array('t_voluntarios', 'Voluntario'), 'IdPublicacion' => array('m_publicaciones', 'Publicaci&oacute;n'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(IdRegistroEstudios)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(NombreEstudiante)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdPublicacion)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Capitulo)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Parrafo)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Observaciones)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(IdRegistroEstudios)%%>', htmlspecialchars($row['IdRegistroEstudios'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdRegistroEstudios)%%>', urlencode($urow['IdRegistroEstudios']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', htmlspecialchars($row['IdPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode($urow['IdPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdVoluntario)%%>', htmlspecialchars($row['IdVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdVoluntario)%%>', urlencode($urow['IdVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(NombreEstudiante)%%>', htmlspecialchars($row['NombreEstudiante'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NombreEstudiante)%%>', urlencode($urow['NombreEstudiante']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPublicacion)%%>', htmlspecialchars($row['IdPublicacion'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPublicacion)%%>', urlencode($urow['IdPublicacion']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Capitulo)%%>', htmlspecialchars($row['Capitulo'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Capitulo)%%>', urlencode($urow['Capitulo']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Parrafo)%%>', htmlspecialchars($row['Parrafo'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Parrafo)%%>', urlencode($urow['Parrafo']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Observaciones)%%>', htmlspecialchars($row['Observaciones'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Observaciones)%%>', urlencode($urow['Observaciones']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(IdRegistroEstudios)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdRegistroEstudios)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(NombreEstudiante)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NombreEstudiante)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPublicacion)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPublicacion)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Capitulo)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Capitulo)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Parrafo)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Parrafo)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Observaciones)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Observaciones)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: t_registro_estudios_dv
	if(function_exists('t_registro_estudios_dv')){
		$args=array();
		t_registro_estudios_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>