<?php

// Data functions (insert, update, delete, form) for table t_turnos_hermanos_maestro

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function t_turnos_hermanos_maestro_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('t_turnos_hermanos_maestro');
	if(!$arrPerm[1]){
		return false;
	}

	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['IdDiaSemana'] = makeSafe($_REQUEST['IdDiaSemana']);
		if($data['IdDiaSemana'] == empty_lookup_value){ $data['IdDiaSemana'] = ''; }
	$data['IdTurno'] = makeSafe($_REQUEST['IdTurno']);
		if($data['IdTurno'] == empty_lookup_value){ $data['IdTurno'] = ''; }
	$data['IdVoluntario'] = makeSafe($_REQUEST['IdVoluntario']);
		if($data['IdVoluntario'] == empty_lookup_value){ $data['IdVoluntario'] = ''; }
	$data['IdResponsabilidad'] = makeSafe($_REQUEST['IdResponsabilidad']);
		if($data['IdResponsabilidad'] == empty_lookup_value){ $data['IdResponsabilidad'] = ''; }

	// hook: t_turnos_hermanos_maestro_before_insert
	if(function_exists('t_turnos_hermanos_maestro_before_insert')){
		$args=array();
		if(!t_turnos_hermanos_maestro_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `t_turnos_hermanos_maestro` set       `IdPPAM`=' . (($data['IdPPAM'] !== '' && $data['IdPPAM'] !== NULL) ? "'{$data['IdPPAM']}'" : 'NULL') . ', `IdDiaSemana`=' . (($data['IdDiaSemana'] !== '' && $data['IdDiaSemana'] !== NULL) ? "'{$data['IdDiaSemana']}'" : 'NULL') . ', `IdTurno`=' . (($data['IdTurno'] !== '' && $data['IdTurno'] !== NULL) ? "'{$data['IdTurno']}'" : 'NULL') . ', `IdVoluntario`=' . (($data['IdVoluntario'] !== '' && $data['IdVoluntario'] !== NULL) ? "'{$data['IdVoluntario']}'" : 'NULL') . ', `IdResponsabilidad`=' . (($data['IdResponsabilidad'] !== '' && $data['IdResponsabilidad'] !== NULL) ? "'{$data['IdResponsabilidad']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"t_turnos_hermanos_maestro_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: t_turnos_hermanos_maestro_after_insert
	if(function_exists('t_turnos_hermanos_maestro_after_insert')){
		$res = sql("select * from `t_turnos_hermanos_maestro` where `IdTurnoHermanoMaestro`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!t_turnos_hermanos_maestro_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='t_turnos_hermanos_maestro', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function t_turnos_hermanos_maestro_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('t_turnos_hermanos_maestro');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: t_turnos_hermanos_maestro_before_delete
	if(function_exists('t_turnos_hermanos_maestro_before_delete')){
		$args=array();
		if(!t_turnos_hermanos_maestro_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `t_turnos_hermanos_maestro` where `IdTurnoHermanoMaestro`='$selected_id'", $eo);

	// hook: t_turnos_hermanos_maestro_after_delete
	if(function_exists('t_turnos_hermanos_maestro_after_delete')){
		$args=array();
		t_turnos_hermanos_maestro_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='$selected_id'", $eo);
}

function t_turnos_hermanos_maestro_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('t_turnos_hermanos_maestro');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['IdDiaSemana'] = makeSafe($_REQUEST['IdDiaSemana']);
		if($data['IdDiaSemana'] == empty_lookup_value){ $data['IdDiaSemana'] = ''; }
	$data['IdTurno'] = makeSafe($_REQUEST['IdTurno']);
		if($data['IdTurno'] == empty_lookup_value){ $data['IdTurno'] = ''; }
	$data['IdVoluntario'] = makeSafe($_REQUEST['IdVoluntario']);
		if($data['IdVoluntario'] == empty_lookup_value){ $data['IdVoluntario'] = ''; }
	$data['IdResponsabilidad'] = makeSafe($_REQUEST['IdResponsabilidad']);
		if($data['IdResponsabilidad'] == empty_lookup_value){ $data['IdResponsabilidad'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: t_turnos_hermanos_maestro_before_update
	if(function_exists('t_turnos_hermanos_maestro_before_update')){
		$args=array();
		if(!t_turnos_hermanos_maestro_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `t_turnos_hermanos_maestro` set       `IdPPAM`=' . (($data['IdPPAM'] !== '' && $data['IdPPAM'] !== NULL) ? "'{$data['IdPPAM']}'" : 'NULL') . ', `IdDiaSemana`=' . (($data['IdDiaSemana'] !== '' && $data['IdDiaSemana'] !== NULL) ? "'{$data['IdDiaSemana']}'" : 'NULL') . ', `IdTurno`=' . (($data['IdTurno'] !== '' && $data['IdTurno'] !== NULL) ? "'{$data['IdTurno']}'" : 'NULL') . ', `IdVoluntario`=' . (($data['IdVoluntario'] !== '' && $data['IdVoluntario'] !== NULL) ? "'{$data['IdVoluntario']}'" : 'NULL') . ', `IdResponsabilidad`=' . (($data['IdResponsabilidad'] !== '' && $data['IdResponsabilidad'] !== NULL) ? "'{$data['IdResponsabilidad']}'" : 'NULL') . " where `IdTurnoHermanoMaestro`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="t_turnos_hermanos_maestro_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: t_turnos_hermanos_maestro_after_update
	if(function_exists('t_turnos_hermanos_maestro_after_update')){
		$res = sql("SELECT * FROM `t_turnos_hermanos_maestro` WHERE `IdTurnoHermanoMaestro`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['IdTurnoHermanoMaestro'];
		$args = array();
		if(!t_turnos_hermanos_maestro_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='t_turnos_hermanos_maestro' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function t_turnos_hermanos_maestro_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('t_turnos_hermanos_maestro');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_IdPPAM = thisOr(undo_magic_quotes($_REQUEST['filterer_IdPPAM']), '');
	$filterer_IdDiaSemana = thisOr(undo_magic_quotes($_REQUEST['filterer_IdDiaSemana']), '');
	$filterer_IdTurno = thisOr(undo_magic_quotes($_REQUEST['filterer_IdTurno']), '');
	$filterer_IdVoluntario = thisOr(undo_magic_quotes($_REQUEST['filterer_IdVoluntario']), '');
	$filterer_IdResponsabilidad = thisOr(undo_magic_quotes($_REQUEST['filterer_IdResponsabilidad']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_IdVoluntario && !$filterer_IdPPAM) $filterer_IdPPAM = sqlValue("select IdPPAM from t_disponibilidades_voluntarios where IdDisponibilidad='" . makeSafe($filterer_IdVoluntario) . "'");
	if($filterer_IdVoluntario && !$filterer_IdDiaSemana) $filterer_IdDiaSemana = sqlValue("select IdDiaSemana from t_disponibilidades_voluntarios where IdDisponibilidad='" . makeSafe($filterer_IdVoluntario) . "'");
	if($filterer_IdVoluntario && !$filterer_IdTurno) $filterer_IdTurno = sqlValue("select IdTurnoDisponible from t_disponibilidades_voluntarios where IdDisponibilidad='" . makeSafe($filterer_IdVoluntario) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: IdPPAM
	$combo_IdPPAM = new DataCombo;
	// combobox: IdDiaSemana
	$combo_IdDiaSemana = new DataCombo;
	// combobox: IdTurno
	$combo_IdTurno = new DataCombo;
	// combobox: IdVoluntario, filterable by: IdPPAM,IdDiaSemana,IdTurno
	$combo_IdVoluntario = new DataCombo;
	// combobox: IdResponsabilidad
	$combo_IdResponsabilidad = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_turnos_hermanos_maestro' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `t_turnos_hermanos_maestro` where `IdTurnoHermanoMaestro`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_IdPPAM->SelectedData = $row['IdPPAM'];
		$combo_IdDiaSemana->SelectedData = $row['IdDiaSemana'];
		$combo_IdTurno->SelectedData = $row['IdTurno'];
		$combo_IdVoluntario->SelectedData = $row['IdVoluntario'];
		$combo_IdResponsabilidad->SelectedData = $row['IdResponsabilidad'];
	}else{
		$combo_IdPPAM->SelectedData = $filterer_IdPPAM;
		$combo_IdDiaSemana->SelectedData = $filterer_IdDiaSemana;
		$combo_IdTurno->SelectedData = $filterer_IdTurno;
		$combo_IdVoluntario->SelectedData = $filterer_IdVoluntario;
		$combo_IdResponsabilidad->SelectedData = $filterer_IdResponsabilidad;
	}
	$combo_IdPPAM->HTML = '<span id="IdPPAM-container' . $rnd1 . '"></span><input type="hidden" name="IdPPAM" id="IdPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPPAM->MatchText = '<span id="IdPPAM-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdPPAM" id="IdPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdDiaSemana->HTML = '<span id="IdDiaSemana-container' . $rnd1 . '"></span><input type="hidden" name="IdDiaSemana" id="IdDiaSemana' . $rnd1 . '" value="' . htmlspecialchars($combo_IdDiaSemana->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdDiaSemana->MatchText = '<span id="IdDiaSemana-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdDiaSemana" id="IdDiaSemana' . $rnd1 . '" value="' . htmlspecialchars($combo_IdDiaSemana->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdTurno->HTML = '<span id="IdTurno-container' . $rnd1 . '"></span><input type="hidden" name="IdTurno" id="IdTurno' . $rnd1 . '" value="' . htmlspecialchars($combo_IdTurno->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdTurno->MatchText = '<span id="IdTurno-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdTurno" id="IdTurno' . $rnd1 . '" value="' . htmlspecialchars($combo_IdTurno->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdVoluntario->HTML = '<span id="IdVoluntario-container' . $rnd1 . '"></span><input type="hidden" name="IdVoluntario" id="IdVoluntario' . $rnd1 . '" value="' . htmlspecialchars($combo_IdVoluntario->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdVoluntario->MatchText = '<span id="IdVoluntario-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdVoluntario" id="IdVoluntario' . $rnd1 . '" value="' . htmlspecialchars($combo_IdVoluntario->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdResponsabilidad->HTML = '<span id="IdResponsabilidad-container' . $rnd1 . '"></span><input type="hidden" name="IdResponsabilidad" id="IdResponsabilidad' . $rnd1 . '" value="' . htmlspecialchars($combo_IdResponsabilidad->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdResponsabilidad->MatchText = '<span id="IdResponsabilidad-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdResponsabilidad" id="IdResponsabilidad' . $rnd1 . '" value="' . htmlspecialchars($combo_IdResponsabilidad->SelectedData, ENT_QUOTES, 'UTF-8') . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_IdPPAM__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdPPAM'] : $filterer_IdPPAM); ?>"};
		var current_IdDiaSemana__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdDiaSemana'] : $filterer_IdDiaSemana); ?>"};
		var current_IdTurno__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdTurno'] : $filterer_IdTurno); ?>"};
		var current_IdVoluntario__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdVoluntario'] : $filterer_IdVoluntario); ?>"};
		var current_IdResponsabilidad__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdResponsabilidad'] : $filterer_IdResponsabilidad); ?>"};

		jQuery(function() {
			if(typeof(IdPPAM_reload__RAND__) == 'function') IdPPAM_reload__RAND__();
			if(typeof(IdDiaSemana_reload__RAND__) == 'function') IdDiaSemana_reload__RAND__();
			if(typeof(IdTurno_reload__RAND__) == 'function') IdTurno_reload__RAND__();
			<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(IdVoluntario_reload__RAND__) == \'function\') IdVoluntario_reload__RAND__(current_IdPPAM__RAND__.value, current_IdDiaSemana__RAND__.value, current_IdTurno__RAND__.value);' : ''); ?>
			if(typeof(IdResponsabilidad_reload__RAND__) == 'function') IdResponsabilidad_reload__RAND__();
		});
		function IdPPAM_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdPPAM-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdPPAM__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdPPAM' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdPPAM"]').val(resp.results[0].id);
						jQuery('[id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__(current_IdPPAM__RAND__.value, $F('IdDiaSemana'), $F('IdTurno'));

						if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_turnos_hermanos_maestro', f: 'IdPPAM' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdPPAM__RAND__.value = e.added.id;
				current_IdPPAM__RAND__.text = e.added.text;
				jQuery('[name="IdPPAM"]').val(e.added.id);

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__(current_IdPPAM__RAND__.value, $F('IdDiaSemana'), $F('IdTurno'));

				if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
			});

			if(!$j("#IdPPAM-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdPPAM__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdPPAM' }
				}).done(function(resp){
					$j('[name="IdPPAM"]').val(resp.results[0].id);
					$j('[id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdPPAM__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdPPAM' }
			}).done(function(resp){
				jQuery('[id=IdPPAM-container__RAND__], [id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdDiaSemana_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdDiaSemana-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdDiaSemana__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdDiaSemana' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdDiaSemana"]').val(resp.results[0].id);
						jQuery('[id=IdDiaSemana-container-readonly__RAND__]').html('<span id="IdDiaSemana-match-text">' + resp.results[0].text + '</span>');

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__($F('IdPPAM'), current_IdDiaSemana__RAND__.value, $F('IdTurno'));

						if(typeof(IdDiaSemana_update_autofills__RAND__) == 'function') IdDiaSemana_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_turnos_hermanos_maestro', f: 'IdDiaSemana' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdDiaSemana__RAND__.value = e.added.id;
				current_IdDiaSemana__RAND__.text = e.added.text;
				jQuery('[name="IdDiaSemana"]').val(e.added.id);

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__($F('IdPPAM'), current_IdDiaSemana__RAND__.value, $F('IdTurno'));

				if(typeof(IdDiaSemana_update_autofills__RAND__) == 'function') IdDiaSemana_update_autofills__RAND__();
			});

			if(!$j("#IdDiaSemana-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdDiaSemana__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdDiaSemana' }
				}).done(function(resp){
					$j('[name="IdDiaSemana"]').val(resp.results[0].id);
					$j('[id=IdDiaSemana-container-readonly__RAND__]').html('<span id="IdDiaSemana-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdDiaSemana_update_autofills__RAND__) == 'function') IdDiaSemana_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdDiaSemana__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdDiaSemana' }
			}).done(function(resp){
				jQuery('[id=IdDiaSemana-container__RAND__], [id=IdDiaSemana-container-readonly__RAND__]').html('<span id="IdDiaSemana-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdDiaSemana_update_autofills__RAND__) == 'function') IdDiaSemana_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdTurno_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdTurno-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdTurno__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdTurno' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdTurno"]').val(resp.results[0].id);
						jQuery('[id=IdTurno-container-readonly__RAND__]').html('<span id="IdTurno-match-text">' + resp.results[0].text + '</span>');

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__($F('IdPPAM'), $F('IdDiaSemana'), current_IdTurno__RAND__.value);

						if(typeof(IdTurno_update_autofills__RAND__) == 'function') IdTurno_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_turnos_hermanos_maestro', f: 'IdTurno' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdTurno__RAND__.value = e.added.id;
				current_IdTurno__RAND__.text = e.added.text;
				jQuery('[name="IdTurno"]').val(e.added.id);

						if(typeof(IdVoluntario_reload__RAND__) == 'function') IdVoluntario_reload__RAND__($F('IdPPAM'), $F('IdDiaSemana'), current_IdTurno__RAND__.value);

				if(typeof(IdTurno_update_autofills__RAND__) == 'function') IdTurno_update_autofills__RAND__();
			});

			if(!$j("#IdTurno-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdTurno__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdTurno' }
				}).done(function(resp){
					$j('[name="IdTurno"]').val(resp.results[0].id);
					$j('[id=IdTurno-container-readonly__RAND__]').html('<span id="IdTurno-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdTurno_update_autofills__RAND__) == 'function') IdTurno_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdTurno__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdTurno' }
			}).done(function(resp){
				jQuery('[id=IdTurno-container__RAND__], [id=IdTurno-container-readonly__RAND__]').html('<span id="IdTurno-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdTurno_update_autofills__RAND__) == 'function') IdTurno_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdVoluntario_reload__RAND__(filterer_IdPPAM, filterer_IdDiaSemana, filterer_IdTurno){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdVoluntario-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_IdPPAM: filterer_IdPPAM, filterer_IdDiaSemana: filterer_IdDiaSemana, filterer_IdTurno: filterer_IdTurno, id: current_IdVoluntario__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdVoluntario' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdVoluntario"]').val(resp.results[0].id);
						jQuery('[id=IdVoluntario-container-readonly__RAND__]').html('<span id="IdVoluntario-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { filterer_IdPPAM: filterer_IdPPAM, filterer_IdDiaSemana: filterer_IdDiaSemana, filterer_IdTurno: filterer_IdTurno, s: term, p: page, t: 't_turnos_hermanos_maestro', f: 'IdVoluntario' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdVoluntario__RAND__.value = e.added.id;
				current_IdVoluntario__RAND__.text = e.added.text;
				jQuery('[name="IdVoluntario"]').val(e.added.id);


				if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
			});

			if(!$j("#IdVoluntario-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdVoluntario__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdVoluntario' }
				}).done(function(resp){
					$j('[name="IdVoluntario"]').val(resp.results[0].id);
					$j('[id=IdVoluntario-container-readonly__RAND__]').html('<span id="IdVoluntario-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdVoluntario__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdVoluntario' }
			}).done(function(resp){
				jQuery('[id=IdVoluntario-container__RAND__], [id=IdVoluntario-container-readonly__RAND__]').html('<span id="IdVoluntario-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdVoluntario_update_autofills__RAND__) == 'function') IdVoluntario_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdResponsabilidad_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdResponsabilidad-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdResponsabilidad__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdResponsabilidad' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdResponsabilidad"]').val(resp.results[0].id);
						jQuery('[id=IdResponsabilidad-container-readonly__RAND__]').html('<span id="IdResponsabilidad-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdResponsabilidad_update_autofills__RAND__) == 'function') IdResponsabilidad_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_turnos_hermanos_maestro', f: 'IdResponsabilidad' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdResponsabilidad__RAND__.value = e.added.id;
				current_IdResponsabilidad__RAND__.text = e.added.text;
				jQuery('[name="IdResponsabilidad"]').val(e.added.id);


				if(typeof(IdResponsabilidad_update_autofills__RAND__) == 'function') IdResponsabilidad_update_autofills__RAND__();
			});

			if(!$j("#IdResponsabilidad-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdResponsabilidad__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdResponsabilidad' }
				}).done(function(resp){
					$j('[name="IdResponsabilidad"]').val(resp.results[0].id);
					$j('[id=IdResponsabilidad-container-readonly__RAND__]').html('<span id="IdResponsabilidad-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdResponsabilidad_update_autofills__RAND__) == 'function') IdResponsabilidad_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdResponsabilidad__RAND__.value, t: 't_turnos_hermanos_maestro', f: 'IdResponsabilidad' }
			}).done(function(resp){
				jQuery('[id=IdResponsabilidad-container__RAND__], [id=IdResponsabilidad-container-readonly__RAND__]').html('<span id="IdResponsabilidad-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdResponsabilidad_update_autofills__RAND__) == 'function') IdResponsabilidad_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/t_turnos_hermanos_maestro_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle del Registro', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return t_turnos_hermanos_maestro_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return t_turnos_hermanos_maestro_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return t_turnos_hermanos_maestro_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#IdPPAM').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdPPAM_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdDiaSemana').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdDiaSemana_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdTurno').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdTurno_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdVoluntario').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdVoluntario_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdResponsabilidad').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdResponsabilidad_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(IdPPAM)%%>', $combo_IdPPAM->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdPPAM)%%>', $combo_IdPPAM->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdPPAM)%%>', urlencode($combo_IdPPAM->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdDiaSemana)%%>', $combo_IdDiaSemana->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdDiaSemana)%%>', $combo_IdDiaSemana->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdDiaSemana)%%>', urlencode($combo_IdDiaSemana->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdTurno)%%>', $combo_IdTurno->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdTurno)%%>', $combo_IdTurno->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdTurno)%%>', urlencode($combo_IdTurno->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdVoluntario)%%>', $combo_IdVoluntario->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdVoluntario)%%>', $combo_IdVoluntario->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdVoluntario)%%>', urlencode($combo_IdVoluntario->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdResponsabilidad)%%>', $combo_IdResponsabilidad->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdResponsabilidad)%%>', $combo_IdResponsabilidad->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdResponsabilidad)%%>', urlencode($combo_IdResponsabilidad->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'IdPPAM' => array('t_ubicaciones_ppam', 'PPAM'), 'IdDiaSemana' => array('m_dias_semana', 'D&iacute;a de la Semana'), 'IdTurno' => array('t_turnos', 'Turno'), 'IdVoluntario' => array('t_disponibilidades_voluntarios', 'Voluntario'), 'IdResponsabilidad' => array('m_responsabilidades_ppam', 'Responsabilidad'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(IdTurnoHermanoMaestro)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdDiaSemana)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdTurno)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdResponsabilidad)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(IdTurnoHermanoMaestro)%%>', htmlspecialchars($row['IdTurnoHermanoMaestro'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdTurnoHermanoMaestro)%%>', urlencode($urow['IdTurnoHermanoMaestro']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', htmlspecialchars($row['IdPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode($urow['IdPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdDiaSemana)%%>', htmlspecialchars($row['IdDiaSemana'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdDiaSemana)%%>', urlencode($urow['IdDiaSemana']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdTurno)%%>', htmlspecialchars($row['IdTurno'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdTurno)%%>', urlencode($urow['IdTurno']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdVoluntario)%%>', htmlspecialchars($row['IdVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdVoluntario)%%>', urlencode($urow['IdVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdResponsabilidad)%%>', htmlspecialchars($row['IdResponsabilidad'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdResponsabilidad)%%>', urlencode($urow['IdResponsabilidad']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(IdTurnoHermanoMaestro)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdTurnoHermanoMaestro)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdDiaSemana)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdDiaSemana)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdTurno)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdTurno)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdResponsabilidad)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdResponsabilidad)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: t_turnos_hermanos_maestro_dv
	if(function_exists('t_turnos_hermanos_maestro_dv')){
		$args=array();
		t_turnos_hermanos_maestro_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>