<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/t_turnos_hermanos_maestro.php");
	include("$currDir/t_turnos_hermanos_maestro_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('t_turnos_hermanos_maestro');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "t_turnos_hermanos_maestro";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`" => "IdTurnoHermanoMaestro",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "IdPPAM",
		"IF(    CHAR_LENGTH(`m_dias_semana1`.`DescDiaSemana`), CONCAT_WS('',   `m_dias_semana1`.`DescDiaSemana`), '') /* D&iacute;a de la Semana */" => "IdDiaSemana",
		"IF(    CHAR_LENGTH(`t_turnos1`.`DescTurno`), CONCAT_WS('',   `t_turnos1`.`DescTurno`), '') /* Turno */" => "IdTurno",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "IdVoluntario",
		"IF(    CHAR_LENGTH(`m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), CONCAT_WS('',   `m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), '') /* Responsabilidad */" => "IdResponsabilidad"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`" => "IdTurnoHermanoMaestro",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "IdPPAM",
		"IF(    CHAR_LENGTH(`m_dias_semana1`.`DescDiaSemana`), CONCAT_WS('',   `m_dias_semana1`.`DescDiaSemana`), '') /* D&iacute;a de la Semana */" => "IdDiaSemana",
		"IF(    CHAR_LENGTH(`t_turnos1`.`DescTurno`), CONCAT_WS('',   `t_turnos1`.`DescTurno`), '') /* Turno */" => "IdTurno",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "IdVoluntario",
		"IF(    CHAR_LENGTH(`m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), CONCAT_WS('',   `m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), '') /* Responsabilidad */" => "IdResponsabilidad"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`" => "IdTurnoHermanoMaestro",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "PPAM",
		"IF(    CHAR_LENGTH(`m_dias_semana1`.`DescDiaSemana`), CONCAT_WS('',   `m_dias_semana1`.`DescDiaSemana`), '') /* D&iacute;a de la Semana */" => "D&iacute;a de la Semana",
		"IF(    CHAR_LENGTH(`t_turnos1`.`DescTurno`), CONCAT_WS('',   `t_turnos1`.`DescTurno`), '') /* Turno */" => "Turno",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "Voluntario",
		"IF(    CHAR_LENGTH(`m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), CONCAT_WS('',   `m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), '') /* Responsabilidad */" => "Responsabilidad"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`" => "IdTurnoHermanoMaestro",
		"IF(    CHAR_LENGTH(`t_ubicaciones_ppam1`.`NombrePPAM`), CONCAT_WS('',   `t_ubicaciones_ppam1`.`NombrePPAM`), '') /* PPAM */" => "IdPPAM",
		"IF(    CHAR_LENGTH(`m_dias_semana1`.`DescDiaSemana`), CONCAT_WS('',   `m_dias_semana1`.`DescDiaSemana`), '') /* D&iacute;a de la Semana */" => "IdDiaSemana",
		"IF(    CHAR_LENGTH(`t_turnos1`.`DescTurno`), CONCAT_WS('',   `t_turnos1`.`DescTurno`), '') /* Turno */" => "IdTurno",
		"IF(    CHAR_LENGTH(`t_voluntarios1`.`NombreVoluntario`), CONCAT_WS('',   `t_voluntarios1`.`NombreVoluntario`), '') /* Voluntario */" => "IdVoluntario",
		"IF(    CHAR_LENGTH(`m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), CONCAT_WS('',   `m_responsabilidades_ppam1`.`DescResponsabilidadPPAM`), '') /* Responsabilidad */" => "IdResponsabilidad"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'IdPPAM' => 'PPAM', 'IdDiaSemana' => 'D&iacute;a de la Semana', 'IdTurno' => 'Turno', 'IdVoluntario' => 'Voluntario', 'IdResponsabilidad' => 'Responsabilidad');

	$x->QueryFrom="`t_turnos_hermanos_maestro` LEFT JOIN `t_ubicaciones_ppam` as t_ubicaciones_ppam1 ON `t_ubicaciones_ppam1`.`IdPPAM`=`t_turnos_hermanos_maestro`.`IdPPAM` LEFT JOIN `m_dias_semana` as m_dias_semana1 ON `m_dias_semana1`.`IdDiaSemana`=`t_turnos_hermanos_maestro`.`IdDiaSemana` LEFT JOIN `t_turnos` as t_turnos1 ON `t_turnos1`.`IdTurno`=`t_turnos_hermanos_maestro`.`IdTurno` LEFT JOIN `t_disponibilidades_voluntarios` as t_disponibilidades_voluntarios1 ON `t_disponibilidades_voluntarios1`.`IdDisponibilidad`=`t_turnos_hermanos_maestro`.`IdVoluntario` LEFT JOIN `t_voluntarios` as t_voluntarios1 ON `t_voluntarios1`.`IdVoluntario`=`t_disponibilidades_voluntarios1`.`IdVoluntario` LEFT JOIN `m_responsabilidades_ppam` as m_responsabilidades_ppam1 ON `m_responsabilidades_ppam1`.`IdResponsabilidadPPAM`=`t_turnos_hermanos_maestro`.`IdResponsabilidad` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "t_turnos_hermanos_maestro_view.php";
	$x->RedirectAfterInsert = "t_turnos_hermanos_maestro_view.php?SelectedID=#ID#";
	$x->TableTitle = "Maestro de Turnos";
	$x->TableIcon = "resources/table_icons/blackboard_drawing (2).png";
	$x->PrimaryKey = "`t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`";
//FGS	$x->DefaultSortField = '2';
//FGS	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("PPAM", "D&iacute;a de la Semana", "Turno", "Voluntario", "Responsabilidad");
	$x->ColFieldName = array('IdPPAM', 'IdDiaSemana', 'IdTurno', 'IdVoluntario', 'IdResponsabilidad');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	$x->Template = 'templates/t_turnos_hermanos_maestro_templateTV.html';
	$x->SelectedTemplate = 'templates/t_turnos_hermanos_maestro_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

/* FGS - EL CODIGO ESTA EN EL HOOK
	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`=membership_userrecords.pkValue and membership_userrecords.tableName='t_turnos_hermanos_maestro' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `t_turnos_hermanos_maestro`.`IdTurnoHermanoMaestro`=membership_userrecords.pkValue and membership_userrecords.tableName='t_turnos_hermanos_maestro' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`t_turnos_hermanos_maestro`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
*/	
	// hook: t_turnos_hermanos_maestro_init
	$render=TRUE;
	if(function_exists('t_turnos_hermanos_maestro_init')){
		$args=array();
		$render=t_turnos_hermanos_maestro_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: t_turnos_hermanos_maestro_header
	$headerCode='';
	if(function_exists('t_turnos_hermanos_maestro_header')){
		$args=array();
		$headerCode=t_turnos_hermanos_maestro_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: t_turnos_hermanos_maestro_footer
	$footerCode='';
	if(function_exists('t_turnos_hermanos_maestro_footer')){
		$args=array();
		$footerCode=t_turnos_hermanos_maestro_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>