<?php

// Data functions (insert, update, delete, form) for table t_voluntarios

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function t_voluntarios_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('t_voluntarios');
	if(!$arrPerm[1]){
		return false;
	}

	$data['IdVoluntario'] = makeSafe($_REQUEST['IdVoluntario']);
		if($data['IdVoluntario'] == empty_lookup_value){ $data['IdVoluntario'] = ''; }
	$data['NombreVoluntario'] = makeSafe($_REQUEST['NombreVoluntario']);
		if($data['NombreVoluntario'] == empty_lookup_value){ $data['NombreVoluntario'] = ''; }
	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['TelefonoMovilVoluntario'] = makeSafe($_REQUEST['TelefonoMovilVoluntario']);
		if($data['TelefonoMovilVoluntario'] == empty_lookup_value){ $data['TelefonoMovilVoluntario'] = ''; }
	$data['MailVoluntario'] = makeSafe($_REQUEST['MailVoluntario']);
		if($data['MailVoluntario'] == empty_lookup_value){ $data['MailVoluntario'] = ''; }
	$data['CongregacionVoluntario'] = makeSafe($_REQUEST['CongregacionVoluntario']);
		if($data['CongregacionVoluntario'] == empty_lookup_value){ $data['CongregacionVoluntario'] = ''; }
	$data['Activo'] = makeSafe($_REQUEST['Activo']);
		if($data['Activo'] == empty_lookup_value){ $data['Activo'] = ''; }
	$data['TelefonoFijoVoluntario'] = makeSafe($_REQUEST['TelefonoFijoVoluntario']);
		if($data['TelefonoFijoVoluntario'] == empty_lookup_value){ $data['TelefonoFijoVoluntario'] = ''; }
	$data['IdResponsabilidadCongregacion'] = makeSafe($_REQUEST['IdResponsabilidadCongregacion']);
		if($data['IdResponsabilidadCongregacion'] == empty_lookup_value){ $data['IdResponsabilidadCongregacion'] = ''; }
	$data['IdResponsabilidadPPAM'] = makeSafe($_REQUEST['IdResponsabilidadPPAM']);
		if($data['IdResponsabilidadPPAM'] == empty_lookup_value){ $data['IdResponsabilidadPPAM'] = ''; }
	$data['IdPrivilegiosServicio'] = makeSafe($_REQUEST['IdPrivilegiosServicio']);
		if($data['IdPrivilegiosServicio'] == empty_lookup_value){ $data['IdPrivilegiosServicio'] = ''; }
	if($data['IdVoluntario'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'IdVoluntario': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: t_voluntarios_before_insert
	if(function_exists('t_voluntarios_before_insert')){
		$args=array();
		if(!t_voluntarios_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `t_voluntarios` set       `NombreVoluntario`=' . (($data['NombreVoluntario'] !== '' && $data['NombreVoluntario'] !== NULL) ? "'{$data['NombreVoluntario']}'" : 'NULL') . ', `IdPPAM`=' . (($data['IdPPAM'] !== '' && $data['IdPPAM'] !== NULL) ? "'{$data['IdPPAM']}'" : 'NULL') . ', `TelefonoMovilVoluntario`=' . (($data['TelefonoMovilVoluntario'] !== '' && $data['TelefonoMovilVoluntario'] !== NULL) ? "'{$data['TelefonoMovilVoluntario']}'" : 'NULL') . ', `MailVoluntario`=' . (($data['MailVoluntario'] !== '' && $data['MailVoluntario'] !== NULL) ? "'{$data['MailVoluntario']}'" : 'NULL') . ', `CongregacionVoluntario`=' . (($data['CongregacionVoluntario'] !== '' && $data['CongregacionVoluntario'] !== NULL) ? "'{$data['CongregacionVoluntario']}'" : 'NULL') . ', `Activo`=' . (($data['Activo'] !== '' && $data['Activo'] !== NULL) ? "'{$data['Activo']}'" : 'NULL') . ', `TelefonoFijoVoluntario`=' . (($data['TelefonoFijoVoluntario'] !== '' && $data['TelefonoFijoVoluntario'] !== NULL) ? "'{$data['TelefonoFijoVoluntario']}'" : 'NULL') . ', `IdResponsabilidadCongregacion`=' . (($data['IdResponsabilidadCongregacion'] !== '' && $data['IdResponsabilidadCongregacion'] !== NULL) ? "'{$data['IdResponsabilidadCongregacion']}'" : 'NULL') . ', `IdResponsabilidadPPAM`=' . (($data['IdResponsabilidadPPAM'] !== '' && $data['IdResponsabilidadPPAM'] !== NULL) ? "'{$data['IdResponsabilidadPPAM']}'" : 'NULL') . ', `IdPrivilegiosServicio`=' . (($data['IdPrivilegiosServicio'] !== '' && $data['IdPrivilegiosServicio'] !== NULL) ? "'{$data['IdPrivilegiosServicio']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"t_voluntarios_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['IdVoluntario'];

	// hook: t_voluntarios_after_insert
	if(function_exists('t_voluntarios_after_insert')){
		$res = sql("select * from `t_voluntarios` where `IdVoluntario`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!t_voluntarios_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='t_voluntarios', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function t_voluntarios_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('t_voluntarios');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_voluntarios' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_voluntarios' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: t_voluntarios_before_delete
	if(function_exists('t_voluntarios_before_delete')){
		$args=array();
		if(!t_voluntarios_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: t_registros_publicaciones_ppam_publicador
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_registros_publicaciones_ppam_publicador` where `IdVoluntario`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_registros_publicaciones_ppam_publicador", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_registros_publicaciones_ppam_publicador", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_registro_estudios
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_registro_estudios` where `IdVoluntario`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_registro_estudios", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_registro_estudios", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_incidencias
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_incidencias` where `IdVoluntario`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_incidencias", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_incidencias", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_turnos_hermanos
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_turnos_hermanos` where `IdVoluntario`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_turnos_hermanos", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_turnos_hermanos", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_colaboraciones_ppam
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_colaboraciones_ppam` where `IdVoluntario`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_colaboraciones_ppam", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_colaboraciones_ppam", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_disponibilidades_voluntarios
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_disponibilidades_voluntarios` where `IdVoluntario`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_disponibilidades_voluntarios", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_disponibilidades_voluntarios", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_ciudades_ppam
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_ciudades_ppam` where `IdCoordinador`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_ciudades_ppam
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_ciudades_ppam` where `idAuxiliarCoordinador1`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_ciudades_ppam
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_ciudades_ppam` where `idAuxiliarCoordinador2`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: t_ciudades_ppam
	$res = sql("select `IdVoluntario` from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);
	$IdVoluntario = db_fetch_row($res);
	$rires = sql("select count(1) from `t_ciudades_ppam` where `idAuxiliarCoordinador3`='".addslashes($IdVoluntario[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "t_ciudades_ppam", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='t_voluntarios_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `t_voluntarios` where `IdVoluntario`='$selected_id'", $eo);

	// hook: t_voluntarios_after_delete
	if(function_exists('t_voluntarios_after_delete')){
		$args=array();
		t_voluntarios_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='t_voluntarios' and pkValue='$selected_id'", $eo);
}

function t_voluntarios_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('t_voluntarios');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_voluntarios' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_voluntarios' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['IdVoluntario'] = makeSafe($_REQUEST['IdVoluntario']);
		if($data['IdVoluntario'] == empty_lookup_value){ $data['IdVoluntario'] = ''; }
	$data['NombreVoluntario'] = makeSafe($_REQUEST['NombreVoluntario']);
		if($data['NombreVoluntario'] == empty_lookup_value){ $data['NombreVoluntario'] = ''; }
	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['TelefonoMovilVoluntario'] = makeSafe($_REQUEST['TelefonoMovilVoluntario']);
		if($data['TelefonoMovilVoluntario'] == empty_lookup_value){ $data['TelefonoMovilVoluntario'] = ''; }
	$data['MailVoluntario'] = makeSafe($_REQUEST['MailVoluntario']);
		if($data['MailVoluntario'] == empty_lookup_value){ $data['MailVoluntario'] = ''; }
	$data['CongregacionVoluntario'] = makeSafe($_REQUEST['CongregacionVoluntario']);
		if($data['CongregacionVoluntario'] == empty_lookup_value){ $data['CongregacionVoluntario'] = ''; }
	$data['Activo'] = makeSafe($_REQUEST['Activo']);
		if($data['Activo'] == empty_lookup_value){ $data['Activo'] = ''; }
	$data['TelefonoFijoVoluntario'] = makeSafe($_REQUEST['TelefonoFijoVoluntario']);
		if($data['TelefonoFijoVoluntario'] == empty_lookup_value){ $data['TelefonoFijoVoluntario'] = ''; }
	$data['IdResponsabilidadCongregacion'] = makeSafe($_REQUEST['IdResponsabilidadCongregacion']);
		if($data['IdResponsabilidadCongregacion'] == empty_lookup_value){ $data['IdResponsabilidadCongregacion'] = ''; }
	$data['IdResponsabilidadPPAM'] = makeSafe($_REQUEST['IdResponsabilidadPPAM']);
		if($data['IdResponsabilidadPPAM'] == empty_lookup_value){ $data['IdResponsabilidadPPAM'] = ''; }
	$data['IdPrivilegiosServicio'] = makeSafe($_REQUEST['IdPrivilegiosServicio']);
		if($data['IdPrivilegiosServicio'] == empty_lookup_value){ $data['IdPrivilegiosServicio'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: t_voluntarios_before_update
	if(function_exists('t_voluntarios_before_update')){
		$args=array();
		if(!t_voluntarios_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `t_voluntarios` set       `NombreVoluntario`=' . (($data['NombreVoluntario'] !== '' && $data['NombreVoluntario'] !== NULL) ? "'{$data['NombreVoluntario']}'" : 'NULL') . ', `IdPPAM`=' . (($data['IdPPAM'] !== '' && $data['IdPPAM'] !== NULL) ? "'{$data['IdPPAM']}'" : 'NULL') . ', `TelefonoMovilVoluntario`=' . (($data['TelefonoMovilVoluntario'] !== '' && $data['TelefonoMovilVoluntario'] !== NULL) ? "'{$data['TelefonoMovilVoluntario']}'" : 'NULL') . ', `MailVoluntario`=' . (($data['MailVoluntario'] !== '' && $data['MailVoluntario'] !== NULL) ? "'{$data['MailVoluntario']}'" : 'NULL') . ', `CongregacionVoluntario`=' . (($data['CongregacionVoluntario'] !== '' && $data['CongregacionVoluntario'] !== NULL) ? "'{$data['CongregacionVoluntario']}'" : 'NULL') . ', `Activo`=' . (($data['Activo'] !== '' && $data['Activo'] !== NULL) ? "'{$data['Activo']}'" : 'NULL') . ', `TelefonoFijoVoluntario`=' . (($data['TelefonoFijoVoluntario'] !== '' && $data['TelefonoFijoVoluntario'] !== NULL) ? "'{$data['TelefonoFijoVoluntario']}'" : 'NULL') . ', `IdResponsabilidadCongregacion`=' . (($data['IdResponsabilidadCongregacion'] !== '' && $data['IdResponsabilidadCongregacion'] !== NULL) ? "'{$data['IdResponsabilidadCongregacion']}'" : 'NULL') . ', `IdResponsabilidadPPAM`=' . (($data['IdResponsabilidadPPAM'] !== '' && $data['IdResponsabilidadPPAM'] !== NULL) ? "'{$data['IdResponsabilidadPPAM']}'" : 'NULL') . ', `IdPrivilegiosServicio`=' . (($data['IdPrivilegiosServicio'] !== '' && $data['IdPrivilegiosServicio'] !== NULL) ? "'{$data['IdPrivilegiosServicio']}'" : 'NULL') . " where `IdVoluntario`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="t_voluntarios_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['IdVoluntario'];

	// hook: t_voluntarios_after_update
	if(function_exists('t_voluntarios_after_update')){
		$res = sql("SELECT * FROM `t_voluntarios` WHERE `IdVoluntario`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['IdVoluntario'];
		$args = array();
		if(!t_voluntarios_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['IdVoluntario']}' where tableName='t_voluntarios' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function t_voluntarios_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('t_voluntarios');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_IdPPAM = thisOr(undo_magic_quotes($_REQUEST['filterer_IdPPAM']), '');
	$filterer_IdResponsabilidadCongregacion = thisOr(undo_magic_quotes($_REQUEST['filterer_IdResponsabilidadCongregacion']), '');
	$filterer_IdResponsabilidadPPAM = thisOr(undo_magic_quotes($_REQUEST['filterer_IdResponsabilidadPPAM']), '');
	$filterer_IdPrivilegiosServicio = thisOr(undo_magic_quotes($_REQUEST['filterer_IdPrivilegiosServicio']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: IdPPAM
	$combo_IdPPAM = new DataCombo;
	// combobox: IdResponsabilidadCongregacion
	$combo_IdResponsabilidadCongregacion = new DataCombo;
	// combobox: IdResponsabilidadPPAM
	$combo_IdResponsabilidadPPAM = new DataCombo;
	// combobox: IdPrivilegiosServicio
	$combo_IdPrivilegiosServicio = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='t_voluntarios' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='t_voluntarios' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `t_voluntarios` where `IdVoluntario`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_IdPPAM->SelectedData = $row['IdPPAM'];
		$combo_IdResponsabilidadCongregacion->SelectedData = $row['IdResponsabilidadCongregacion'];
		$combo_IdResponsabilidadPPAM->SelectedData = $row['IdResponsabilidadPPAM'];
		$combo_IdPrivilegiosServicio->SelectedData = $row['IdPrivilegiosServicio'];
	}else{
		$combo_IdPPAM->SelectedData = $filterer_IdPPAM;
		$combo_IdResponsabilidadCongregacion->SelectedData = $filterer_IdResponsabilidadCongregacion;
		$combo_IdResponsabilidadPPAM->SelectedData = $filterer_IdResponsabilidadPPAM;
		$combo_IdPrivilegiosServicio->SelectedData = $filterer_IdPrivilegiosServicio;
	}
	$combo_IdPPAM->HTML = '<span id="IdPPAM-container' . $rnd1 . '"></span><input type="hidden" name="IdPPAM" id="IdPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPPAM->MatchText = '<span id="IdPPAM-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdPPAM" id="IdPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdResponsabilidadCongregacion->HTML = '<span id="IdResponsabilidadCongregacion-container' . $rnd1 . '"></span><input type="hidden" name="IdResponsabilidadCongregacion" id="IdResponsabilidadCongregacion' . $rnd1 . '" value="' . htmlspecialchars($combo_IdResponsabilidadCongregacion->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdResponsabilidadCongregacion->MatchText = '<span id="IdResponsabilidadCongregacion-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdResponsabilidadCongregacion" id="IdResponsabilidadCongregacion' . $rnd1 . '" value="' . htmlspecialchars($combo_IdResponsabilidadCongregacion->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdResponsabilidadPPAM->HTML = '<span id="IdResponsabilidadPPAM-container' . $rnd1 . '"></span><input type="hidden" name="IdResponsabilidadPPAM" id="IdResponsabilidadPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdResponsabilidadPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdResponsabilidadPPAM->MatchText = '<span id="IdResponsabilidadPPAM-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdResponsabilidadPPAM" id="IdResponsabilidadPPAM' . $rnd1 . '" value="' . htmlspecialchars($combo_IdResponsabilidadPPAM->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPrivilegiosServicio->HTML = '<span id="IdPrivilegiosServicio-container' . $rnd1 . '"></span><input type="hidden" name="IdPrivilegiosServicio" id="IdPrivilegiosServicio' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPrivilegiosServicio->SelectedData, ENT_QUOTES, 'UTF-8') . '">';
	$combo_IdPrivilegiosServicio->MatchText = '<span id="IdPrivilegiosServicio-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IdPrivilegiosServicio" id="IdPrivilegiosServicio' . $rnd1 . '" value="' . htmlspecialchars($combo_IdPrivilegiosServicio->SelectedData, ENT_QUOTES, 'UTF-8') . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_IdPPAM__RAND__ = { text: "<?php echo ($selected_id ? '' : '<%%idppam%%>'); ?>", value: "<?php echo addslashes($selected_id ? $urow['IdPPAM'] : $filterer_IdPPAM); ?>"};
		var current_IdResponsabilidadCongregacion__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdResponsabilidadCongregacion'] : $filterer_IdResponsabilidadCongregacion); ?>"};
		var current_IdResponsabilidadPPAM__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdResponsabilidadPPAM'] : $filterer_IdResponsabilidadPPAM); ?>"};
		var current_IdPrivilegiosServicio__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IdPrivilegiosServicio'] : $filterer_IdPrivilegiosServicio); ?>"};

		jQuery(function() {
			if(typeof(IdPPAM_reload__RAND__) == 'function') IdPPAM_reload__RAND__();
			if(typeof(IdResponsabilidadCongregacion_reload__RAND__) == 'function') IdResponsabilidadCongregacion_reload__RAND__();
			if(typeof(IdResponsabilidadPPAM_reload__RAND__) == 'function') IdResponsabilidadPPAM_reload__RAND__();
			if(typeof(IdPrivilegiosServicio_reload__RAND__) == 'function') IdPrivilegiosServicio_reload__RAND__();
		});
		function IdPPAM_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdPPAM-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						<?php if(!$selected_id && !$filterer_IdPPAM){ ?>
							data: { text: '<%%idppam%%>', t: 't_voluntarios', f: 'IdPPAM' }
						<?php }else{ ?>
							data: { id: current_IdPPAM__RAND__.value, t: 't_voluntarios', f: 'IdPPAM' }
						<?php } ?>

					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdPPAM"]').val(resp.results[0].id);
						jQuery('[id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_voluntarios', f: 'IdPPAM' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdPPAM__RAND__.value = e.added.id;
				current_IdPPAM__RAND__.text = e.added.text;
				jQuery('[name="IdPPAM"]').val(e.added.id);


				if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
			});

			if(!$j("#IdPPAM-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdPPAM__RAND__.value, t: 't_voluntarios', f: 'IdPPAM' }
				}).done(function(resp){
					$j('[name="IdPPAM"]').val(resp.results[0].id);
					$j('[id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdPPAM__RAND__.value, t: 't_voluntarios', f: 'IdPPAM' }
			}).done(function(resp){
				jQuery('[id=IdPPAM-container__RAND__], [id=IdPPAM-container-readonly__RAND__]').html('<span id="IdPPAM-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdPPAM_update_autofills__RAND__) == 'function') IdPPAM_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdResponsabilidadCongregacion_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdResponsabilidadCongregacion-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdResponsabilidadCongregacion__RAND__.value, t: 't_voluntarios', f: 'IdResponsabilidadCongregacion' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdResponsabilidadCongregacion"]').val(resp.results[0].id);
						jQuery('[id=IdResponsabilidadCongregacion-container-readonly__RAND__]').html('<span id="IdResponsabilidadCongregacion-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdResponsabilidadCongregacion_update_autofills__RAND__) == 'function') IdResponsabilidadCongregacion_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_voluntarios', f: 'IdResponsabilidadCongregacion' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdResponsabilidadCongregacion__RAND__.value = e.added.id;
				current_IdResponsabilidadCongregacion__RAND__.text = e.added.text;
				jQuery('[name="IdResponsabilidadCongregacion"]').val(e.added.id);


				if(typeof(IdResponsabilidadCongregacion_update_autofills__RAND__) == 'function') IdResponsabilidadCongregacion_update_autofills__RAND__();
			});

			if(!$j("#IdResponsabilidadCongregacion-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdResponsabilidadCongregacion__RAND__.value, t: 't_voluntarios', f: 'IdResponsabilidadCongregacion' }
				}).done(function(resp){
					$j('[name="IdResponsabilidadCongregacion"]').val(resp.results[0].id);
					$j('[id=IdResponsabilidadCongregacion-container-readonly__RAND__]').html('<span id="IdResponsabilidadCongregacion-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdResponsabilidadCongregacion_update_autofills__RAND__) == 'function') IdResponsabilidadCongregacion_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdResponsabilidadCongregacion__RAND__.value, t: 't_voluntarios', f: 'IdResponsabilidadCongregacion' }
			}).done(function(resp){
				jQuery('[id=IdResponsabilidadCongregacion-container__RAND__], [id=IdResponsabilidadCongregacion-container-readonly__RAND__]').html('<span id="IdResponsabilidadCongregacion-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdResponsabilidadCongregacion_update_autofills__RAND__) == 'function') IdResponsabilidadCongregacion_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdResponsabilidadPPAM_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdResponsabilidadPPAM-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdResponsabilidadPPAM__RAND__.value, t: 't_voluntarios', f: 'IdResponsabilidadPPAM' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdResponsabilidadPPAM"]').val(resp.results[0].id);
						jQuery('[id=IdResponsabilidadPPAM-container-readonly__RAND__]').html('<span id="IdResponsabilidadPPAM-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdResponsabilidadPPAM_update_autofills__RAND__) == 'function') IdResponsabilidadPPAM_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_voluntarios', f: 'IdResponsabilidadPPAM' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdResponsabilidadPPAM__RAND__.value = e.added.id;
				current_IdResponsabilidadPPAM__RAND__.text = e.added.text;
				jQuery('[name="IdResponsabilidadPPAM"]').val(e.added.id);


				if(typeof(IdResponsabilidadPPAM_update_autofills__RAND__) == 'function') IdResponsabilidadPPAM_update_autofills__RAND__();
			});

			if(!$j("#IdResponsabilidadPPAM-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdResponsabilidadPPAM__RAND__.value, t: 't_voluntarios', f: 'IdResponsabilidadPPAM' }
				}).done(function(resp){
					$j('[name="IdResponsabilidadPPAM"]').val(resp.results[0].id);
					$j('[id=IdResponsabilidadPPAM-container-readonly__RAND__]').html('<span id="IdResponsabilidadPPAM-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdResponsabilidadPPAM_update_autofills__RAND__) == 'function') IdResponsabilidadPPAM_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdResponsabilidadPPAM__RAND__.value, t: 't_voluntarios', f: 'IdResponsabilidadPPAM' }
			}).done(function(resp){
				jQuery('[id=IdResponsabilidadPPAM-container__RAND__], [id=IdResponsabilidadPPAM-container-readonly__RAND__]').html('<span id="IdResponsabilidadPPAM-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdResponsabilidadPPAM_update_autofills__RAND__) == 'function') IdResponsabilidadPPAM_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function IdPrivilegiosServicio_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#IdPrivilegiosServicio-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_IdPrivilegiosServicio__RAND__.value, t: 't_voluntarios', f: 'IdPrivilegiosServicio' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="IdPrivilegiosServicio"]').val(resp.results[0].id);
						jQuery('[id=IdPrivilegiosServicio-container-readonly__RAND__]').html('<span id="IdPrivilegiosServicio-match-text">' + resp.results[0].text + '</span>');


						if(typeof(IdPrivilegiosServicio_update_autofills__RAND__) == 'function') IdPrivilegiosServicio_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 't_voluntarios', f: 'IdPrivilegiosServicio' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_IdPrivilegiosServicio__RAND__.value = e.added.id;
				current_IdPrivilegiosServicio__RAND__.text = e.added.text;
				jQuery('[name="IdPrivilegiosServicio"]').val(e.added.id);


				if(typeof(IdPrivilegiosServicio_update_autofills__RAND__) == 'function') IdPrivilegiosServicio_update_autofills__RAND__();
			});

			if(!$j("#IdPrivilegiosServicio-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_IdPrivilegiosServicio__RAND__.value, t: 't_voluntarios', f: 'IdPrivilegiosServicio' }
				}).done(function(resp){
					$j('[name="IdPrivilegiosServicio"]').val(resp.results[0].id);
					$j('[id=IdPrivilegiosServicio-container-readonly__RAND__]').html('<span id="IdPrivilegiosServicio-match-text">' + resp.results[0].text + '</span>');

					if(typeof(IdPrivilegiosServicio_update_autofills__RAND__) == 'function') IdPrivilegiosServicio_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_IdPrivilegiosServicio__RAND__.value, t: 't_voluntarios', f: 'IdPrivilegiosServicio' }
			}).done(function(resp){
				jQuery('[id=IdPrivilegiosServicio-container__RAND__], [id=IdPrivilegiosServicio-container-readonly__RAND__]').html('<span id="IdPrivilegiosServicio-match-text">' + resp.results[0].text + '</span>');

				if(typeof(IdPrivilegiosServicio_update_autofills__RAND__) == 'function') IdPrivilegiosServicio_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/t_voluntarios_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle del Registro', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return t_voluntarios_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return t_voluntarios_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return t_voluntarios_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#NombreVoluntario').replaceWith('<div class=\"form-control-static\" id=\"NombreVoluntario\">' + (jQuery('#NombreVoluntario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#IdPPAM').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdPPAM_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#TelefonoMovilVoluntario').replaceWith('<div class=\"form-control-static\" id=\"TelefonoMovilVoluntario\">' + (jQuery('#TelefonoMovilVoluntario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#MailVoluntario').replaceWith('<div class=\"form-control-static\" id=\"MailVoluntario\">' + (jQuery('#MailVoluntario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CongregacionVoluntario').replaceWith('<div class=\"form-control-static\" id=\"CongregacionVoluntario\">' + (jQuery('#CongregacionVoluntario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Activo').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#TelefonoFijoVoluntario').replaceWith('<div class=\"form-control-static\" id=\"TelefonoFijoVoluntario\">' + (jQuery('#TelefonoFijoVoluntario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#IdResponsabilidadCongregacion').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdResponsabilidadCongregacion_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdResponsabilidadPPAM').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdResponsabilidadPPAM_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#IdPrivilegiosServicio').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IdPrivilegiosServicio_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(IdPPAM)%%>', $combo_IdPPAM->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdPPAM)%%>', $combo_IdPPAM->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdPPAM)%%>', urlencode($combo_IdPPAM->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdResponsabilidadCongregacion)%%>', $combo_IdResponsabilidadCongregacion->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdResponsabilidadCongregacion)%%>', $combo_IdResponsabilidadCongregacion->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdResponsabilidadCongregacion)%%>', urlencode($combo_IdResponsabilidadCongregacion->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdResponsabilidadPPAM)%%>', $combo_IdResponsabilidadPPAM->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdResponsabilidadPPAM)%%>', $combo_IdResponsabilidadPPAM->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdResponsabilidadPPAM)%%>', urlencode($combo_IdResponsabilidadPPAM->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(IdPrivilegiosServicio)%%>', $combo_IdPrivilegiosServicio->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(IdPrivilegiosServicio)%%>', $combo_IdPrivilegiosServicio->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(IdPrivilegiosServicio)%%>', urlencode($combo_IdPrivilegiosServicio->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'IdPPAM' => array('t_ubicaciones_ppam', 'PPAM'), 'IdResponsabilidadCongregacion' => array('m_responsabilidades_congregacion', 'IdResponsabilidadCongregacion'), 'IdResponsabilidadPPAM' => array('m_responsabilidades_ppam', 'IdResponsabilidadPPAM'), 'IdPrivilegiosServicio' => array('m_privilegios_servicio', 'IdPrivilegiosServicio'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(IdVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(NombreVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(TelefonoMovilVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MailVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CongregacionVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Activo)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(TelefonoFijoVoluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdResponsabilidadCongregacion)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdResponsabilidadPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdPrivilegiosServicio)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(IdVoluntario)%%>', htmlspecialchars($row['IdVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdVoluntario)%%>', urlencode($urow['IdVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(NombreVoluntario)%%>', htmlspecialchars($row['NombreVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NombreVoluntario)%%>', urlencode($urow['NombreVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', htmlspecialchars($row['IdPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode($urow['IdPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(TelefonoMovilVoluntario)%%>', htmlspecialchars($row['TelefonoMovilVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TelefonoMovilVoluntario)%%>', urlencode($urow['TelefonoMovilVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(MailVoluntario)%%>', htmlspecialchars($row['MailVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MailVoluntario)%%>', urlencode($urow['MailVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CongregacionVoluntario)%%>', htmlspecialchars($row['CongregacionVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CongregacionVoluntario)%%>', urlencode($urow['CongregacionVoluntario']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Activo)%%>', ($row['Activo'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(TelefonoFijoVoluntario)%%>', htmlspecialchars($row['TelefonoFijoVoluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TelefonoFijoVoluntario)%%>', urlencode($urow['TelefonoFijoVoluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdResponsabilidadCongregacion)%%>', htmlspecialchars($row['IdResponsabilidadCongregacion'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdResponsabilidadCongregacion)%%>', urlencode($urow['IdResponsabilidadCongregacion']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdResponsabilidadPPAM)%%>', htmlspecialchars($row['IdResponsabilidadPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdResponsabilidadPPAM)%%>', urlencode($urow['IdResponsabilidadPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPrivilegiosServicio)%%>', htmlspecialchars($row['IdPrivilegiosServicio'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPrivilegiosServicio)%%>', urlencode($urow['IdPrivilegiosServicio']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(IdVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(NombreVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NombreVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', '<%%idppam%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode('<%%idppam%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(TelefonoMovilVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TelefonoMovilVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(MailVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MailVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CongregacionVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CongregacionVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Activo)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(TelefonoFijoVoluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TelefonoFijoVoluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdResponsabilidadCongregacion)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdResponsabilidadCongregacion)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdResponsabilidadPPAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdResponsabilidadPPAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPrivilegiosServicio)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPrivilegiosServicio)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: t_voluntarios_dv
	if(function_exists('t_voluntarios_dv')){
		$args=array();
		t_voluntarios_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>