<?php

// Data functions (insert, update, delete, form) for table v_informemensualporpublicador

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function v_informemensualporpublicador_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('v_informemensualporpublicador');
	if(!$arrPerm[1]){
		return false;
	}

	$data['id'] = makeSafe($_REQUEST['id']);
		if($data['id'] == empty_lookup_value){ $data['id'] = ''; }
	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['ppam'] = makeSafe($_REQUEST['ppam']);
		if($data['ppam'] == empty_lookup_value){ $data['ppam'] = ''; }
	$data['fecha'] = makeSafe($_REQUEST['fecha']);
		if($data['fecha'] == empty_lookup_value){ $data['fecha'] = ''; }
	$data['voluntario'] = makeSafe($_REQUEST['voluntario']);
		if($data['voluntario'] == empty_lookup_value){ $data['voluntario'] = ''; }
	$data['publicacion'] = makeSafe($_REQUEST['publicacion']);
		if($data['publicacion'] == empty_lookup_value){ $data['publicacion'] = ''; }
	$data['totalesmes'] = makeSafe($_REQUEST['totalesmes']);
		if($data['totalesmes'] == empty_lookup_value){ $data['totalesmes'] = ''; }
	if($data['id'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Id': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: v_informemensualporpublicador_before_insert
	if(function_exists('v_informemensualporpublicador_before_insert')){
		$args=array();
		if(!v_informemensualporpublicador_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `v_informemensualporpublicador` set       `ppam`=' . (($data['ppam'] !== '' && $data['ppam'] !== NULL) ? "'{$data['ppam']}'" : 'NULL') . ', `fecha`=' . (($data['fecha'] !== '' && $data['fecha'] !== NULL) ? "'{$data['fecha']}'" : 'NULL') . ', `voluntario`=' . (($data['voluntario'] !== '' && $data['voluntario'] !== NULL) ? "'{$data['voluntario']}'" : 'NULL') . ', `publicacion`=' . (($data['publicacion'] !== '' && $data['publicacion'] !== NULL) ? "'{$data['publicacion']}'" : 'NULL') . ', `totalesmes`=' . (($data['totalesmes'] !== '' && $data['totalesmes'] !== NULL) ? "'{$data['totalesmes']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"v_informemensualporpublicador_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['id'];

	// hook: v_informemensualporpublicador_after_insert
	if(function_exists('v_informemensualporpublicador_after_insert')){
		$res = sql("select * from `v_informemensualporpublicador` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!v_informemensualporpublicador_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='v_informemensualporpublicador', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function v_informemensualporpublicador_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('v_informemensualporpublicador');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: v_informemensualporpublicador_before_delete
	if(function_exists('v_informemensualporpublicador_before_delete')){
		$args=array();
		if(!v_informemensualporpublicador_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `v_informemensualporpublicador` where `id`='$selected_id'", $eo);

	// hook: v_informemensualporpublicador_after_delete
	if(function_exists('v_informemensualporpublicador_after_delete')){
		$args=array();
		v_informemensualporpublicador_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='$selected_id'", $eo);
}

function v_informemensualporpublicador_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('v_informemensualporpublicador');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['id'] = makeSafe($_REQUEST['id']);
		if($data['id'] == empty_lookup_value){ $data['id'] = ''; }
	$data['IdPPAM'] = makeSafe($_REQUEST['IdPPAM']);
		if($data['IdPPAM'] == empty_lookup_value){ $data['IdPPAM'] = ''; }
	$data['ppam'] = makeSafe($_REQUEST['ppam']);
		if($data['ppam'] == empty_lookup_value){ $data['ppam'] = ''; }
	$data['fecha'] = makeSafe($_REQUEST['fecha']);
		if($data['fecha'] == empty_lookup_value){ $data['fecha'] = ''; }
	$data['voluntario'] = makeSafe($_REQUEST['voluntario']);
		if($data['voluntario'] == empty_lookup_value){ $data['voluntario'] = ''; }
	$data['publicacion'] = makeSafe($_REQUEST['publicacion']);
		if($data['publicacion'] == empty_lookup_value){ $data['publicacion'] = ''; }
	$data['totalesmes'] = makeSafe($_REQUEST['totalesmes']);
		if($data['totalesmes'] == empty_lookup_value){ $data['totalesmes'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: v_informemensualporpublicador_before_update
	if(function_exists('v_informemensualporpublicador_before_update')){
		$args=array();
		if(!v_informemensualporpublicador_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `v_informemensualporpublicador` set       `ppam`=' . (($data['ppam'] !== '' && $data['ppam'] !== NULL) ? "'{$data['ppam']}'" : 'NULL') . ', `fecha`=' . (($data['fecha'] !== '' && $data['fecha'] !== NULL) ? "'{$data['fecha']}'" : 'NULL') . ', `voluntario`=' . (($data['voluntario'] !== '' && $data['voluntario'] !== NULL) ? "'{$data['voluntario']}'" : 'NULL') . ', `publicacion`=' . (($data['publicacion'] !== '' && $data['publicacion'] !== NULL) ? "'{$data['publicacion']}'" : 'NULL') . ', `totalesmes`=' . (($data['totalesmes'] !== '' && $data['totalesmes'] !== NULL) ? "'{$data['totalesmes']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="v_informemensualporpublicador_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['id'];

	// hook: v_informemensualporpublicador_after_update
	if(function_exists('v_informemensualporpublicador_after_update')){
		$res = sql("SELECT * FROM `v_informemensualporpublicador` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!v_informemensualporpublicador_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['id']}' where tableName='v_informemensualporpublicador' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function v_informemensualporpublicador_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('v_informemensualporpublicador');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='v_informemensualporpublicador' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `v_informemensualporpublicador` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/v_informemensualporpublicador_templateDV.html');

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle del Registro', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return v_informemensualporpublicador_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return v_informemensualporpublicador_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return v_informemensualporpublicador_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ppam').replaceWith('<div class=\"form-control-static\" id=\"ppam\">' + (jQuery('#ppam').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fecha').replaceWith('<div class=\"form-control-static\" id=\"fecha\">' + (jQuery('#fecha').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#voluntario').replaceWith('<div class=\"form-control-static\" id=\"voluntario\">' + (jQuery('#voluntario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#publicacion').replaceWith('<div class=\"form-control-static\" id=\"publicacion\">' + (jQuery('#publicacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#totalesmes').replaceWith('<div class=\"form-control-static\" id=\"totalesmes\">' + (jQuery('#totalesmes').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(IdPPAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ppam)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(fecha)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(voluntario)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(publicacion)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(totalesmes)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', htmlspecialchars($row['IdPPAM'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode($urow['IdPPAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ppam)%%>', htmlspecialchars($row['ppam'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ppam)%%>', urlencode($urow['ppam']), $templateCode);
		$templateCode=str_replace('<%%VALUE(fecha)%%>', htmlspecialchars($row['fecha'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fecha)%%>', urlencode($urow['fecha']), $templateCode);
		$templateCode=str_replace('<%%VALUE(voluntario)%%>', htmlspecialchars($row['voluntario'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(voluntario)%%>', urlencode($urow['voluntario']), $templateCode);
		$templateCode=str_replace('<%%VALUE(publicacion)%%>', htmlspecialchars($row['publicacion'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(publicacion)%%>', urlencode($urow['publicacion']), $templateCode);
		$templateCode=str_replace('<%%VALUE(totalesmes)%%>', htmlspecialchars($row['totalesmes'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(totalesmes)%%>', urlencode($urow['totalesmes']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(IdPPAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(IdPPAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ppam)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ppam)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(fecha)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fecha)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(voluntario)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(voluntario)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(publicacion)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(publicacion)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(totalesmes)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(totalesmes)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: v_informemensualporpublicador_dv
	if(function_exists('v_informemensualporpublicador_dv')){
		$args=array();
		v_informemensualporpublicador_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>