<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/v_informemensualporciudad.php");
	include("$currDir/v_informemensualporciudad_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('v_informemensualporciudad');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "v_informemensualporciudad";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`v_informemensualporciudad`.`id`" => "id",
		"`v_informemensualporciudad`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`v_informemensualporciudad`.`ciudadppam`" => "ciudadppam",
		"`v_informemensualporciudad`.`fecha`" => "fecha",
		"`v_informemensualporciudad`.`publicacion`" => "publicacion",
		"`v_informemensualporciudad`.`totalesmes`" => "totalesmes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`v_informemensualporciudad`.`id`" => "id",
		"`v_informemensualporciudad`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`v_informemensualporciudad`.`ciudadppam`" => "ciudadppam",
		"`v_informemensualporciudad`.`fecha`" => "fecha",
		"`v_informemensualporciudad`.`publicacion`" => "publicacion",
		"`v_informemensualporciudad`.`totalesmes`" => "totalesmes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`v_informemensualporciudad`.`id`" => "Id",
		"`v_informemensualporciudad`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`v_informemensualporciudad`.`ciudadppam`" => "Ciudad PPAM",
		"`v_informemensualporciudad`.`fecha`" => "Fecha",
		"`v_informemensualporciudad`.`publicacion`" => "Publicaci&oacute;n",
		"`v_informemensualporciudad`.`totalesmes`" => "Totales Mes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`v_informemensualporciudad`.`id`" => "id",
		"`v_informemensualporciudad`.`IdCiudadPPAM`" => "IdCiudadPPAM",
		"`v_informemensualporciudad`.`ciudadppam`" => "ciudadppam",
		"`v_informemensualporciudad`.`fecha`" => "fecha",
		"`v_informemensualporciudad`.`publicacion`" => "publicacion",
		"`v_informemensualporciudad`.`totalesmes`" => "totalesmes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`v_informemensualporciudad` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 30;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "v_informemensualporciudad_view.php";
	$x->RedirectAfterInsert = "v_informemensualporciudad_view.php";
	$x->TableTitle = "Informe Mensual por Ciudad";
	$x->TableIcon = "resources/table_icons/chart_column.png";
	$x->PrimaryKey = "`v_informemensualporciudad`.`id`";
// FGS	$x->DefaultSortField = '3';
// FGS	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Ciudad PPAM", "Fecha", "Publicaci&oacute;n", "Totales Mes");
	$x->ColFieldName = array('ciudadppam', 'fecha', 'publicacion', 'totalesmes');
	$x->ColNumber  = array(3, 4, 5, 6);

	$x->Template = 'templates/v_informemensualporciudad_templateTV.html';
	$x->SelectedTemplate = 'templates/v_informemensualporciudad_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

/* FGS - El código está en el HOOK
	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `v_informemensualporciudad`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='v_informemensualporciudad' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `v_informemensualporciudad`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='v_informemensualporciudad' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`v_informemensualporciudad`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
*/

	// hook: v_informemensualporciudad_init
	$render=TRUE;
	if(function_exists('v_informemensualporciudad_init')){
		$args=array();
		$render=v_informemensualporciudad_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: v_informemensualporciudad_header
	$headerCode='';
	if(function_exists('v_informemensualporciudad_header')){
		$args=array();
		$headerCode=v_informemensualporciudad_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: v_informemensualporciudad_footer
	$footerCode='';
	if(function_exists('v_informemensualporciudad_footer')){
		$args=array();
		$footerCode=v_informemensualporciudad_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>